; spi_15.asm -- GENERATED by verification/firmware_templates.py
; (issue #93). seed=20261009 protocol=spi index=15
; params={"cpha": 1, "cpol": 1, "half_period": 3, "miso": [244], "mode": 3, "mosi": [246]}
; Regenerate: python3 verification/firmware_templates.py --seed 20261009 --out DIR
        LDI   R2, 0x03      ; CS released, SCLK idle
        OUT   UO_OUT, R2
        WAIT  15
; ---- burst 0: MOSI 0xF6
        LDI   R2, 0x02      ; CS asserted
        OUT   UO_OUT, R2
        WAIT  3
        LDI   R1, 0x00
        LDI   R2, 0x06
.cyclesec spi_rand_b0
        OUT   UO_OUT, R1
        IN    R3, UIO_IN
        WAIT  0
        OUT   UO_OUT, R2
        LDI   R2, 0x06
        WAIT  0
        OUT   UO_OUT, R1
        IN    R3, UIO_IN
        WAIT  0
        OUT   UO_OUT, R2
        LDI   R2, 0x06
        WAIT  0
        OUT   UO_OUT, R1
        IN    R3, UIO_IN
        WAIT  0
        OUT   UO_OUT, R2
        LDI   R2, 0x06
        WAIT  0
        OUT   UO_OUT, R1
        IN    R3, UIO_IN
        WAIT  0
        OUT   UO_OUT, R2
        LDI   R2, 0x02
        WAIT  0
        OUT   UO_OUT, R1
        IN    R3, UIO_IN
        WAIT  0
        OUT   UO_OUT, R2
        LDI   R2, 0x06
        WAIT  0
        OUT   UO_OUT, R1
        IN    R3, UIO_IN
        WAIT  0
        OUT   UO_OUT, R2
        LDI   R2, 0x06
        WAIT  0
        OUT   UO_OUT, R1
        IN    R3, UIO_IN
        WAIT  0
        OUT   UO_OUT, R2
        LDI   R2, 0x02
        WAIT  0
        OUT   UO_OUT, R1
        IN    R3, UIO_IN
        WAIT  0
        OUT   UO_OUT, R2
        LDI   R2, 0x00
        WAIT  0
.endcyclesec
        WAIT  3
        LDI   R2, 0x03      ; CS released
        OUT   UO_OUT, R2
        WAIT  31
        HALT
