; uart_rx_18.asm -- GENERATED by verification/firmware_templates.py
; (issue #93). seed=20261009 protocol=uart_rx index=18
; params={"frames": [{"data": 85, "gap_bits": 1.0}], "jitter_frac": 0.0, "period": 50, "program": "uart_rx", "rx_pin": "ui_in[1]", "scale": 1.0, "stim_seed": 31451783, "variation": "nominal"}
; Regenerate: python3 verification/firmware_templates.py --seed 20261009 --out DIR
; Receiver below is firmware/asm/uart_rx.asm byte for byte; the seeded
; part of this case is the stimulus on ui_in[1] (params above).
; uart_rx.asm -- bit-banged 8N1 UART receiver, 50 core cycles per bit.
;
; Issue #91 (rows 1 and 10): the receive direction. The ISA is the product --
; no UART peripheral exists; the receiver is IN (pin read), WAIT (cycle
; count) and ordinary ALU ops.
;
; BIT-PERIOD-CYCLES 50
;
; Nominal 1,000,000 baud at the target 50 MHz clock of target-spec row 4 --
; arithmetic at an unconfirmed clock; the claim is the cycle count.
;
; Pins:
;   RX          UI_IN bit 1 (idle HIGH; DR 0010 target pin plan, USB-bridge
;               option B). UI_IN bit 0 is PROG_SER and plays no part here.
;               Held high by the bench from the MODE drop onward; the program also waits for a high line (`sync`)
;               before arming start detect, so a low line at boot is not a
;               start bit.
;   result      UO_OUT, all 8 bits: the received byte, written as soon as the
;               8th data bit has been sampled; holds until the next frame.
;   sample mark UIO_OUT bit 1: high for the cycles between each `IN` of the
;               line and the following clear. Observability aid so the bench
;               can read the firmware's real sample instants off the pins.
;   frame error UIO_OUT bit 2: set after the stop-bit sample when the stop bit
;               read 0; cleared by the next frame's first sample mark.
;
; Registers: R0 = shift accumulator (bits enter at bit 7, shift right, so
;            the first (LSB) bit lands in bit 0 after 8 shifts)
;            R1 = constant 2 (RX bit mask, XOR mask, sample-mark value and loop
;                 decrement; delay-loop counts below are doubled to match)
;            R2 = pin sample / scratch
;            R3 = constant 0 outside delay loops (strobe clear); the outer
;                 delay counter inside them, back to 0 on exit
;
; Timing, all in core cycles (DR 0001: every instruction 1 cycle, WAIT imm8 =
; imm8 + 1). The start edge is found by a 3-cycle poll (IN, AND, BNZ), so the
; edge is located to within 3 cycles; the first data sample is then placed at
; 1.5 bit periods after detection less the poll/instruction overhead
; (delay 70 cycles after the BNZ falls through), i.e. at the centre of data
; bit 0 to within about +-1.5 cycles. Every later sample is exactly
; 50 cycles after the previous one -- nothing between samples branches on
; pin data. The ONLY pin-dependent branches are the `sync`/`poll` handshake
; loops (wait for line high, wait for start edge) and the single post-stop-bit
; choice between re-arming at once and re-syncing, which is why the assembler's
; data-dependent-latency lint emits exactly three warnings for this program;
; all are start-edge/framing handshakes taken AFTER the last sample of a
; frame or BEFORE the first, never between samples (DR 0001 'Timing model').

        LDI   R1, 2
        LDI   R3, 0
        OUT   UO_OUT, R3       ; result register cleared
        OUT   UIO_OUT, R3      ; marks and error flag cleared
sync:
        IN    R2, UI_IN        ; wait for an idle-high line
        AND   R2, R1
        BZ    sync
poll:
        IN    R2, UI_IN        ; start-edge detect: loop while the line is high
        AND   R2, R1
        BNZ   poll
        WAIT  69            ; 70 cycles
; ---- data bit 0
        IN    R2, UI_IN        ; SAMPLE (bit centre)
        OUT   UIO_OUT, R1      ; sample mark high
        AND   R2, R1
        NOP                    ; RX is bit 1: six shifts reach bit 7; the NOP keeps the 7-cycle slot
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R0, RIGHT        ; make room at bit 7
        OR    R0, R2           ; insert
        OUT   UIO_OUT, R3      ; sample mark low
        WAIT  36            ; 37 cycles
; ---- data bit 1
        IN    R2, UI_IN        ; SAMPLE (bit centre)
        OUT   UIO_OUT, R1      ; sample mark high
        AND   R2, R1
        NOP                    ; RX is bit 1: six shifts reach bit 7; the NOP keeps the 7-cycle slot
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R0, RIGHT        ; make room at bit 7
        OR    R0, R2           ; insert
        OUT   UIO_OUT, R3      ; sample mark low
        WAIT  36            ; 37 cycles
; ---- data bit 2
        IN    R2, UI_IN        ; SAMPLE (bit centre)
        OUT   UIO_OUT, R1      ; sample mark high
        AND   R2, R1
        NOP                    ; RX is bit 1: six shifts reach bit 7; the NOP keeps the 7-cycle slot
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R0, RIGHT        ; make room at bit 7
        OR    R0, R2           ; insert
        OUT   UIO_OUT, R3      ; sample mark low
        WAIT  36            ; 37 cycles
; ---- data bit 3
        IN    R2, UI_IN        ; SAMPLE (bit centre)
        OUT   UIO_OUT, R1      ; sample mark high
        AND   R2, R1
        NOP                    ; RX is bit 1: six shifts reach bit 7; the NOP keeps the 7-cycle slot
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R0, RIGHT        ; make room at bit 7
        OR    R0, R2           ; insert
        OUT   UIO_OUT, R3      ; sample mark low
        WAIT  36            ; 37 cycles
; ---- data bit 4
        IN    R2, UI_IN        ; SAMPLE (bit centre)
        OUT   UIO_OUT, R1      ; sample mark high
        AND   R2, R1
        NOP                    ; RX is bit 1: six shifts reach bit 7; the NOP keeps the 7-cycle slot
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R0, RIGHT        ; make room at bit 7
        OR    R0, R2           ; insert
        OUT   UIO_OUT, R3      ; sample mark low
        WAIT  36            ; 37 cycles
; ---- data bit 5
        IN    R2, UI_IN        ; SAMPLE (bit centre)
        OUT   UIO_OUT, R1      ; sample mark high
        AND   R2, R1
        NOP                    ; RX is bit 1: six shifts reach bit 7; the NOP keeps the 7-cycle slot
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R0, RIGHT        ; make room at bit 7
        OR    R0, R2           ; insert
        OUT   UIO_OUT, R3      ; sample mark low
        WAIT  36            ; 37 cycles
; ---- data bit 6
        IN    R2, UI_IN        ; SAMPLE (bit centre)
        OUT   UIO_OUT, R1      ; sample mark high
        AND   R2, R1
        NOP                    ; RX is bit 1: six shifts reach bit 7; the NOP keeps the 7-cycle slot
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R0, RIGHT        ; make room at bit 7
        OR    R0, R2           ; insert
        OUT   UIO_OUT, R3      ; sample mark low
        WAIT  36            ; 37 cycles
; ---- data bit 7
        IN    R2, UI_IN        ; SAMPLE (bit centre)
        OUT   UIO_OUT, R1      ; sample mark high
        AND   R2, R1
        NOP                    ; RX is bit 1: six shifts reach bit 7; the NOP keeps the 7-cycle slot
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R2, LEFT         ; move the sampled bit up to bit 7
        SHF   R0, RIGHT        ; make room at bit 7
        OR    R0, R2           ; insert
        OUT   UIO_OUT, R3      ; sample mark low
        OUT   UO_OUT, R0       ; emit the received byte
        WAIT  35            ; 36 cycles
; ---- stop bit
        IN    R2, UI_IN        ; SAMPLE the stop bit
        OUT   UIO_OUT, R1      ; sample mark high
        AND   R2, R1
        XOR   R2, R1           ; 1 when the stop bit read 0 (framing error)
        SHF   R2, LEFT         ; -> UIO_OUT bit 2 (SHF leaves Z alone)
        OUT   UIO_OUT, R2      ; also clears the mark
        BZ    poll             ; clean stop bit: re-arm start detect at once
        JMP   sync             ; stop bit read 0: wait for the line to go high first
