; i2c_01.asm -- GENERATED by verification/firmware_templates.py
; (issue #93). seed=20261009 protocol=i2c index=1
; params={"ack_address": true, "address": 99, "data": 0, "grade": "i2c_std"}
; Regenerate: python3 verification/firmware_templates.py --seed 20261009 --out DIR
; Bit engine below is firmware/asm/i2c_std.asm byte for byte except the
; address/data LDI R0 immediates (and, in a negative control only,
; the low-phase WAIT literal): per-phase cycle budgets are the
; committed program's.
; ---------------------------------------------------------------- setup
        LDI   R1, 0x80        ; bit mask / "SCL low, SDA released" pins
        LDI   R2, 0x01        ; SCL bit, OR-ed in for the high phase
        LDI   R3, 0x81        ; both lines released: bus idle
        OUT   UIO_OUT, R3
        WAIT  255             ; > 1 SCL period of guaranteed idle

; --------------------------------------------------------------- START
        LDI   R3, 0x01        ; SCL high, SDA low
.cyclesec i2c_start
        OUT   UIO_OUT, R3     ; START: SDA falls while SCL high
        WAIT  200              ; 61 cycles
        LDI   R0, 0xC6        ; address byte 0x50<<1|W, MSB first
        MOV   R3, R0
        AND   R3, R1          ; R3 = SDA(bit 1 = 1), SCL low
.endcyclesec                   ; t_HD;STA = 65 cycles
; ---------------------------------------------- address byte 0xA0, MSB first
.cyclesec i2c_abit1_low
        OUT   UIO_OUT, R3     ; SCL falls; SDA rises (bit 1 = 1) in low
        WAIT  232              ; 233 cycles
        OR    R3, R2          ; raise SCL, SDA unchanged
.endcyclesec                   ; t_LOW = 65
.cyclesec i2c_abit1_high
        OUT   UIO_OUT, R3     ; SCL rises: bit 1 sampled on the line
        SHF   R0, LEFT        ; bit 2 into position
        WAIT  195              ; 56 cycles
        MOV   R3, R0
        AND   R3, R1          ; R3 = SDA(bit 2), SCL low
.endcyclesec                   ; t_HIGH = 60
.cyclesec i2c_abit2_low
        OUT   UIO_OUT, R3
        WAIT  232
        OR    R3, R2
.endcyclesec
.cyclesec i2c_abit2_high
        OUT   UIO_OUT, R3
        SHF   R0, LEFT
        WAIT  195
        MOV   R3, R0
        AND   R3, R1
.endcyclesec
.cyclesec i2c_abit3_low
        OUT   UIO_OUT, R3
        WAIT  232
        OR    R3, R2
.endcyclesec
.cyclesec i2c_abit3_high
        OUT   UIO_OUT, R3
        SHF   R0, LEFT
        WAIT  195
        MOV   R3, R0
        AND   R3, R1
.endcyclesec
.cyclesec i2c_abit4_low
        OUT   UIO_OUT, R3
        WAIT  232
        OR    R3, R2
.endcyclesec
.cyclesec i2c_abit4_high
        OUT   UIO_OUT, R3
        SHF   R0, LEFT
        WAIT  195
        MOV   R3, R0
        AND   R3, R1
.endcyclesec
.cyclesec i2c_abit5_low
        OUT   UIO_OUT, R3
        WAIT  232
        OR    R3, R2
.endcyclesec
.cyclesec i2c_abit5_high
        OUT   UIO_OUT, R3
        SHF   R0, LEFT
        WAIT  195
        MOV   R3, R0
        AND   R3, R1
.endcyclesec
.cyclesec i2c_abit6_low
        OUT   UIO_OUT, R3
        WAIT  232
        OR    R3, R2
.endcyclesec
.cyclesec i2c_abit6_high
        OUT   UIO_OUT, R3
        SHF   R0, LEFT
        WAIT  195
        MOV   R3, R0
        AND   R3, R1
.endcyclesec
.cyclesec i2c_abit7_low
        OUT   UIO_OUT, R3
        WAIT  232
        OR    R3, R2
.endcyclesec
.cyclesec i2c_abit7_high
        OUT   UIO_OUT, R3
        SHF   R0, LEFT
        WAIT  195
        MOV   R3, R0
        AND   R3, R1
.endcyclesec
.cyclesec i2c_abit8_low
        OUT   UIO_OUT, R3
        WAIT  232
        OR    R3, R2
.endcyclesec
.cyclesec i2c_abit8_high
        OUT   UIO_OUT, R3     ; last address clock rises
        WAIT  197              ; 58 cycles (the ACK prep is one MOV)
        MOV   R3, R1          ; 0x80: SDA released for the ACK slot
.endcyclesec                   ; t_HIGH = 60
; ------------------------------------- address ACK slot (the branch point)
.cyclesec i2c_ack1_low
        OUT   UIO_OUT, R3     ; SCL falls; SDA released
        WAIT  30              ; 21 cycles: the bench's peripheral pulls
                               ; SDA low two cycles after seeing this
                               ; fall, well before the sample below
        IN    R3, UIO_IN      ; sample the bus (taints R3)
        WAIT  199              ; 39 cycles
        AND   R3, R1          ; isolate SDA (bit 7); sets Z -- and the
                               ; flags must survive to the BNZ, so the rise
                               ; pins are built with LDI (not flag-setting),
                               ; never MOV/OR which would clobber Z
        LDI   R3, 0x81        ; SCL high, SDA released
.endcyclesec                   ; t_LOW = 65
.cyclesec i2c_ack1_high
        OUT   UIO_OUT, R3     ; SCL rises: ACK/NACK is the line level AT
                               ; this edge; sampled above at IN
        WAIT  194              ; 55 cycles
        BNZ   stop_from_addr  ; SDA read 1 = NACK -> STOP. The one
                               ; sanctioned data-dependent branch; the
                               ; assembler warns about exactly this line
        LDI   R0, 0x00        ; the data byte (ACK path)
        MOV   R3, R0
        AND   R3, R1          ; R3 = SDA(bit 1 = 0), SCL low
.endcyclesec                   ; t_HIGH = 60
; ------------------------------------------------ data byte 0x5A, MSB first
.cyclesec i2c_dbit1_low
        OUT   UIO_OUT, R3     ; SCL falls; SDA falls (bit 1 = 0) in low
        WAIT  232
        OR    R3, R2
.endcyclesec
.cyclesec i2c_dbit1_high
        OUT   UIO_OUT, R3
        SHF   R0, LEFT
        WAIT  195
        MOV   R3, R0
        AND   R3, R1
.endcyclesec
.cyclesec i2c_dbit2_low
        OUT   UIO_OUT, R3
        WAIT  232
        OR    R3, R2
.endcyclesec
.cyclesec i2c_dbit2_high
        OUT   UIO_OUT, R3
        SHF   R0, LEFT
        WAIT  195
        MOV   R3, R0
        AND   R3, R1
.endcyclesec
.cyclesec i2c_dbit3_low
        OUT   UIO_OUT, R3
        WAIT  232
        OR    R3, R2
.endcyclesec
.cyclesec i2c_dbit3_high
        OUT   UIO_OUT, R3
        SHF   R0, LEFT
        WAIT  195
        MOV   R3, R0
        AND   R3, R1
.endcyclesec
.cyclesec i2c_dbit4_low
        OUT   UIO_OUT, R3
        WAIT  232
        OR    R3, R2
.endcyclesec
.cyclesec i2c_dbit4_high
        OUT   UIO_OUT, R3
        SHF   R0, LEFT
        WAIT  195
        MOV   R3, R0
        AND   R3, R1
.endcyclesec
.cyclesec i2c_dbit5_low
        OUT   UIO_OUT, R3
        WAIT  232
        OR    R3, R2
.endcyclesec
.cyclesec i2c_dbit5_high
        OUT   UIO_OUT, R3
        SHF   R0, LEFT
        WAIT  195
        MOV   R3, R0
        AND   R3, R1
.endcyclesec
.cyclesec i2c_dbit6_low
        OUT   UIO_OUT, R3
        WAIT  232
        OR    R3, R2
.endcyclesec
.cyclesec i2c_dbit6_high
        OUT   UIO_OUT, R3
        SHF   R0, LEFT
        WAIT  195
        MOV   R3, R0
        AND   R3, R1
.endcyclesec
.cyclesec i2c_dbit7_low
        OUT   UIO_OUT, R3
        WAIT  232
        OR    R3, R2
.endcyclesec
.cyclesec i2c_dbit7_high
        OUT   UIO_OUT, R3
        SHF   R0, LEFT
        WAIT  195
        MOV   R3, R0
        AND   R3, R1
.endcyclesec
.cyclesec i2c_dbit8_low
        OUT   UIO_OUT, R3
        WAIT  232
        OR    R3, R2
.endcyclesec
.cyclesec i2c_dbit8_high
        OUT   UIO_OUT, R3     ; last data clock rises
        WAIT  197              ; 58 cycles
        MOV   R3, R1          ; 0x80: SDA released for the ACK slot
.endcyclesec                   ; t_HIGH = 60
; ------------------------------- data ACK slot (sampled, not branched on:
; ------------------------------- the transfer ends after one byte either
; ------------------------------- way -- the branch lives on the address
; ------------------------------- ACK, where its outcome changes the rest)
.cyclesec i2c_ack2_low
        OUT   UIO_OUT, R3     ; SCL falls; SDA released
        WAIT  30              ; 21 cycles
        IN    R3, UIO_IN      ; sample the bus (taints R3)
        WAIT  199              ; 39 cycles
        AND   R3, R1          ; isolate SDA; sets Z (no branch reads it)
        LDI   R3, 0x81
.endcyclesec                   ; t_LOW = 65
.cyclesec i2c_ack2_high
        OUT   UIO_OUT, R3     ; SCL rises
        WAIT  196              ; 57 cycles
        LDI   R3, 0x80        ; SDA released, SCL still high
        WAIT  0               ; 1 cycle: pads the SCL fall to exactly 60
.endcyclesec                   ; t_HIGH = 60
; ------------------------------------------------- STOP from the data ACK
.cyclesec i2c_stop_data_low
        OUT   UIO_OUT, R3     ; SCL falls; SDA still released
        LDI   R3, 0x00        ; SDA low during the low period
        OUT   UIO_OUT, R3     ; SDA falls (while SCL low)
        WAIT  230              ; 61 cycles: pads this low period
        LDI   R3, 0x01        ; SCL high, SDA low
.endcyclesec                   ; 235: the full pre-STOP low period, SCL
                               ; fall to (exclusive) the SCL rise
.cyclesec i2c_stop_data
        OUT   UIO_OUT, R3     ; SCL rises: STOP setup begins
        WAIT  202              ; 58 cycles
        LDI   R3, 0x81        ; SDA released
.endcyclesec                   ; t_SU;STO = 60
        OUT   UIO_OUT, R3     ; SDA rises while SCL high: STOP
        WAIT  255             ; hold the bus idle
        HALT
; ------------------------------------- STOP from a NACKed address (jumped
; ---------- to from i2c_ack1_high's BNZ: same sequence, own copy, so the
; ---------- taken-branch path needs no extra JMP whose cycle would then
; ---------- have to be subtracted from a phase budget. LDI + WAIT 1 land
; ---------- the SCL fall exactly 60 cycles after the ACK clock's rise.)
stop_from_addr:
        LDI   R3, 0x80        ; SDA released, SCL still high
        WAIT  1               ; 2 cycles
.cyclesec i2c_stop_addr_low
        OUT   UIO_OUT, R3     ; SCL falls (at ACK-rise + 60 exactly)
        LDI   R3, 0x00        ; SDA low during the low period
        OUT   UIO_OUT, R3
        WAIT  230
        LDI   R3, 0x01
.endcyclesec                   ; 235: the full pre-STOP low period, SCL
                               ; fall to (exclusive) the SCL rise
.cyclesec i2c_stop_addr
        OUT   UIO_OUT, R3     ; SCL rises: STOP setup begins
        WAIT  202
        LDI   R3, 0x81
.endcyclesec                   ; t_SU;STO = 60
        OUT   UIO_OUT, R3     ; SDA rises while SCL high: STOP
        WAIT  255
        HALT
