// Generated by flow/run-post-layout-sdf.sh (issue #102) -- do not edit.
// Scopes `define FUNCTIONAL to the unmodified vendor SRAM models only.
`define FUNCTIONAL 1
`include "<repo>/rtl/vendor/RM_IHPSG13_1P_256x16_c2_bm_bist.v"
`include "<repo>/rtl/vendor/RM_IHPSG13_1P_core_behavioral_bm_bist.v"
`undef FUNCTIONAL
