; spi_10.asm -- GENERATED by verification/firmware_templates.py
; (issue #93). seed=20261009 protocol=spi index=10
; params={"cpha": 0, "cpol": 1, "half_period": 6, "miso": [117], "mode": 2, "mosi": [170]}
; Regenerate: python3 verification/firmware_templates.py --seed 20261009 --out DIR
        LDI   R2, 0x03      ; CS released, SCLK idle
        OUT   UO_OUT, R2
        WAIT  15
; ---- burst 0: MOSI 0xAA
        LDI   R2, 0x02      ; CS asserted
        OUT   UO_OUT, R2
        WAIT  3
        LDI   R1, 0x02
        LDI   R2, 0x04
.cyclesec spi_rand_b0
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        WAIT  3
        OUT   UO_OUT, R1
        LDI   R2, 0x00
        WAIT  3
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        WAIT  3
        OUT   UO_OUT, R1
        LDI   R2, 0x04
        WAIT  3
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        WAIT  3
        OUT   UO_OUT, R1
        LDI   R2, 0x00
        WAIT  3
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        WAIT  3
        OUT   UO_OUT, R1
        LDI   R2, 0x04
        WAIT  3
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        WAIT  3
        OUT   UO_OUT, R1
        LDI   R2, 0x00
        WAIT  3
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        WAIT  3
        OUT   UO_OUT, R1
        LDI   R2, 0x04
        WAIT  3
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        WAIT  3
        OUT   UO_OUT, R1
        LDI   R2, 0x00
        WAIT  3
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        WAIT  3
        OUT   UO_OUT, R1
        LDI   R2, 0x00
        WAIT  3
.endcyclesec
        WAIT  3
        LDI   R2, 0x03      ; CS released
        OUT   UO_OUT, R2
        WAIT  31
        HALT
