/* Generated by Yosys 0.67+post (git sha1 b8e7da6f40ae8f552c116bf6c359b07c6533e159, Release, GNU /usr/bin/c++ 13.3.0) */

module protocol_program_memory(clk, rst_n, mode_pin, serial_in, fetch_addr, instr_word, run_phase);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input mode_pin;
  wire mode_pin;
  input serial_in;
  wire serial_in;
  input [7:0] fetch_addr;
  wire [7:0] fetch_addr;
  output [15:0] instr_word;
  wire [15:0] instr_word;
  output run_phase;
  wire run_phase;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire [3:0] bit_cnt;
  wire full;
  wire load_active;
  wire [15:0] load_word;
  wire [7:0] mem_addr;
  wire mem_men;
  wire mem_ren;
  wire mem_wen;
  wire run_phase_r;
  wire [14:0] shift_reg;
  wire started;
  wire [7:0] wr_addr;
  sg13cmos5l_inv_1 _056_ (
    .A(load_active),
    .Y(mem_ren)
  );
  sg13cmos5l_inv_1 _057_ (
    .A(wr_addr[2]),
    .Y(_050_)
  );
  sg13cmos5l_inv_1 _058_ (
    .A(wr_addr[7]),
    .Y(_051_)
  );
  sg13cmos5l_mux2_1 _059_ (
    .A0(fetch_addr[6]),
    .A1(wr_addr[6]),
    .S(load_active),
    .X(mem_addr[6])
  );
  sg13cmos5l_mux2_1 _060_ (
    .A0(fetch_addr[5]),
    .A1(wr_addr[5]),
    .S(load_active),
    .X(mem_addr[5])
  );
  sg13cmos5l_mux2_1 _061_ (
    .A0(fetch_addr[4]),
    .A1(wr_addr[4]),
    .S(load_active),
    .X(mem_addr[4])
  );
  sg13cmos5l_mux2_1 _062_ (
    .A0(fetch_addr[3]),
    .A1(wr_addr[3]),
    .S(load_active),
    .X(mem_addr[3])
  );
  sg13cmos5l_nor2_1 _063_ (
    .A(load_active),
    .B(fetch_addr[2]),
    .Y(_052_)
  );
  sg13cmos5l_a21oi_1 _064_ (
    .A1(load_active),
    .A2(_050_),
    .B1(_052_),
    .Y(mem_addr[2])
  );
  sg13cmos5l_mux2_1 _065_ (
    .A0(fetch_addr[1]),
    .A1(wr_addr[1]),
    .S(load_active),
    .X(mem_addr[1])
  );
  sg13cmos5l_mux2_1 _066_ (
    .A0(fetch_addr[0]),
    .A1(wr_addr[0]),
    .S(load_active),
    .X(mem_addr[0])
  );
  sg13cmos5l_nor2_1 _067_ (
    .A(load_active),
    .B(fetch_addr[7]),
    .Y(_053_)
  );
  sg13cmos5l_a21oi_1 _068_ (
    .A1(load_active),
    .A2(_051_),
    .B1(_053_),
    .Y(mem_addr[7])
  );
  sg13cmos5l_nand2_1 _069_ (
    .A(load_active),
    .B(mode_pin),
    .Y(_054_)
  );
  sg13cmos5l_nand4_1 _070_ (
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .C(bit_cnt[2]),
    .D(bit_cnt[3]),
    .Y(_055_)
  );
  sg13cmos5l_nor3_1 _071_ (
    .A(full),
    .B(_054_),
    .C(_055_),
    .Y(mem_wen)
  );
  sg13cmos5l_nand2b_1 _072_ (
    .A_N(mem_wen),
    .B(load_active),
    .Y(mem_men)
  );
  sg13cmos5l_and3_1 _073_ (
    .A(load_active),
    .B(mode_pin),
    .C(started),
    .X(_030_)
  );
  sg13cmos5l_nand3_1 _074_ (
    .A(load_active),
    .B(mode_pin),
    .C(started),
    .Y(_031_)
  );
  sg13cmos5l_mux2_1 _075_ (
    .A0(shift_reg[3]),
    .A1(shift_reg[2]),
    .S(_030_),
    .X(_000_)
  );
  sg13cmos5l_mux2_1 _076_ (
    .A0(shift_reg[2]),
    .A1(shift_reg[1]),
    .S(_030_),
    .X(_001_)
  );
  sg13cmos5l_mux2_1 _077_ (
    .A0(shift_reg[1]),
    .A1(shift_reg[0]),
    .S(_030_),
    .X(_002_)
  );
  sg13cmos5l_mux2_1 _078_ (
    .A0(shift_reg[0]),
    .A1(serial_in),
    .S(_030_),
    .X(_003_)
  );
  sg13cmos5l_nand3_1 _079_ (
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .C(_030_),
    .Y(_032_)
  );
  sg13cmos5l_nand4_1 _080_ (
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .C(bit_cnt[2]),
    .D(_030_),
    .Y(_033_)
  );
  sg13cmos5l_xnor2_1 _081_ (
    .A(bit_cnt[3]),
    .B(_033_),
    .Y(_004_)
  );
  sg13cmos5l_nor3_1 _082_ (
    .A(full),
    .B(_055_),
    .C(_031_),
    .Y(_034_)
  );
  sg13cmos5l_nand3_1 _083_ (
    .A(wr_addr[3]),
    .B(wr_addr[2]),
    .C(wr_addr[1]),
    .Y(_035_)
  );
  sg13cmos5l_nand4_1 _084_ (
    .A(wr_addr[0]),
    .B(wr_addr[6]),
    .C(wr_addr[5]),
    .D(wr_addr[4]),
    .Y(_036_)
  );
  sg13cmos5l_nor2_1 _085_ (
    .A(_035_),
    .B(_036_),
    .Y(_037_)
  );
  sg13cmos5l_or3_1 _086_ (
    .A(_051_),
    .B(_035_),
    .C(_036_),
    .X(_038_)
  );
  sg13cmos5l_nand3_1 _087_ (
    .A(wr_addr[0]),
    .B(_034_),
    .C(_038_),
    .Y(_039_)
  );
  sg13cmos5l_nand4_1 _088_ (
    .A(wr_addr[0]),
    .B(wr_addr[1]),
    .C(_034_),
    .D(_038_),
    .Y(_040_)
  );
  sg13cmos5l_nor2_1 _089_ (
    .A(_050_),
    .B(_040_),
    .Y(_041_)
  );
  sg13cmos5l_xnor2_1 _090_ (
    .A(wr_addr[2]),
    .B(_040_),
    .Y(_005_)
  );
  sg13cmos5l_xnor2_1 _091_ (
    .A(wr_addr[1]),
    .B(_039_),
    .Y(_006_)
  );
  sg13cmos5l_a21o_1 _092_ (
    .A1(_034_),
    .A2(_038_),
    .B1(wr_addr[0]),
    .X(_042_)
  );
  sg13cmos5l_and2_1 _093_ (
    .A(_039_),
    .B(_042_),
    .X(_007_)
  );
  sg13cmos5l_nand3_1 _094_ (
    .A(wr_addr[4]),
    .B(wr_addr[3]),
    .C(_041_),
    .Y(_043_)
  );
  sg13cmos5l_nand4_1 _095_ (
    .A(wr_addr[5]),
    .B(wr_addr[4]),
    .C(wr_addr[3]),
    .D(_041_),
    .Y(_044_)
  );
  sg13cmos5l_xnor2_1 _096_ (
    .A(wr_addr[6]),
    .B(_044_),
    .Y(_008_)
  );
  sg13cmos5l_xnor2_1 _097_ (
    .A(wr_addr[5]),
    .B(_043_),
    .Y(_009_)
  );
  sg13cmos5l_xnor2_1 _098_ (
    .A(bit_cnt[2]),
    .B(_032_),
    .Y(_010_)
  );
  sg13cmos5l_a21o_1 _099_ (
    .A1(bit_cnt[0]),
    .A2(_030_),
    .B1(bit_cnt[1]),
    .X(_045_)
  );
  sg13cmos5l_and2_1 _100_ (
    .A(_032_),
    .B(_045_),
    .X(_011_)
  );
  sg13cmos5l_nor3_1 _101_ (
    .A(_055_),
    .B(_031_),
    .C(_038_),
    .Y(_046_)
  );
  sg13cmos5l_or2_1 _102_ (
    .A(full),
    .B(_046_),
    .X(_012_)
  );
  sg13cmos5l_xnor2_1 _103_ (
    .A(bit_cnt[0]),
    .B(_031_),
    .Y(_013_)
  );
  sg13cmos5l_a21o_1 _104_ (
    .A1(wr_addr[3]),
    .A2(_041_),
    .B1(wr_addr[4]),
    .X(_047_)
  );
  sg13cmos5l_and2_1 _105_ (
    .A(_043_),
    .B(_047_),
    .X(_014_)
  );
  sg13cmos5l_xor2_1 _106_ (
    .A(wr_addr[3]),
    .B(_041_),
    .X(_015_)
  );
  sg13cmos5l_mux2_1 _107_ (
    .A0(shift_reg[13]),
    .A1(shift_reg[12]),
    .S(_030_),
    .X(_016_)
  );
  sg13cmos5l_mux2_1 _108_ (
    .A0(shift_reg[12]),
    .A1(shift_reg[11]),
    .S(_030_),
    .X(_017_)
  );
  sg13cmos5l_a21oi_1 _109_ (
    .A1(mem_ren),
    .A2(started),
    .B1(mode_pin),
    .Y(_048_)
  );
  sg13cmos5l_or2_1 _110_ (
    .A(run_phase_r),
    .B(_048_),
    .X(_018_)
  );
  sg13cmos5l_mux2_1 _111_ (
    .A0(shift_reg[11]),
    .A1(shift_reg[10]),
    .S(_030_),
    .X(_019_)
  );
  sg13cmos5l_mux2_1 _112_ (
    .A0(shift_reg[13]),
    .A1(shift_reg[14]),
    .S(_031_),
    .X(_020_)
  );
  sg13cmos5l_nor2_1 _113_ (
    .A(load_active),
    .B(mode_pin),
    .Y(_049_)
  );
  sg13cmos5l_a21oi_1 _114_ (
    .A1(started),
    .A2(_054_),
    .B1(_049_),
    .Y(_021_)
  );
  sg13cmos5l_a21o_1 _115_ (
    .A1(_034_),
    .A2(_037_),
    .B1(wr_addr[7]),
    .X(_022_)
  );
  sg13cmos5l_mux2_1 _116_ (
    .A0(shift_reg[10]),
    .A1(shift_reg[9]),
    .S(_030_),
    .X(_023_)
  );
  sg13cmos5l_mux2_1 _117_ (
    .A0(shift_reg[9]),
    .A1(shift_reg[8]),
    .S(_030_),
    .X(_024_)
  );
  sg13cmos5l_mux2_1 _118_ (
    .A0(shift_reg[8]),
    .A1(shift_reg[7]),
    .S(_030_),
    .X(_025_)
  );
  sg13cmos5l_mux2_1 _119_ (
    .A0(shift_reg[7]),
    .A1(shift_reg[6]),
    .S(_030_),
    .X(_026_)
  );
  sg13cmos5l_mux2_1 _120_ (
    .A0(shift_reg[6]),
    .A1(shift_reg[5]),
    .S(_030_),
    .X(_027_)
  );
  sg13cmos5l_mux2_1 _121_ (
    .A0(shift_reg[5]),
    .A1(shift_reg[4]),
    .S(_030_),
    .X(_028_)
  );
  sg13cmos5l_mux2_1 _122_ (
    .A0(shift_reg[3]),
    .A1(shift_reg[4]),
    .S(_031_),
    .X(_029_)
  );
  sg13cmos5l_dfrbpq_1 _123_ (
    .CLK(clk),
    .D(_018_),
    .Q(run_phase_r),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _124_ (
    .CLK(clk),
    .D(_013_),
    .Q(bit_cnt[0]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _125_ (
    .CLK(clk),
    .D(_011_),
    .Q(bit_cnt[1]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _126_ (
    .CLK(clk),
    .D(_010_),
    .Q(bit_cnt[2]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _127_ (
    .CLK(clk),
    .D(_004_),
    .Q(bit_cnt[3]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _128_ (
    .CLK(clk),
    .D(_012_),
    .Q(full),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _129_ (
    .CLK(clk),
    .D(_003_),
    .Q(shift_reg[0]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _130_ (
    .CLK(clk),
    .D(_002_),
    .Q(shift_reg[1]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _131_ (
    .CLK(clk),
    .D(_001_),
    .Q(shift_reg[2]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _132_ (
    .CLK(clk),
    .D(_000_),
    .Q(shift_reg[3]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _133_ (
    .CLK(clk),
    .D(_029_),
    .Q(shift_reg[4]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _134_ (
    .CLK(clk),
    .D(_028_),
    .Q(shift_reg[5]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _135_ (
    .CLK(clk),
    .D(_027_),
    .Q(shift_reg[6]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _136_ (
    .CLK(clk),
    .D(_026_),
    .Q(shift_reg[7]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _137_ (
    .CLK(clk),
    .D(_025_),
    .Q(shift_reg[8]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _138_ (
    .CLK(clk),
    .D(_024_),
    .Q(shift_reg[9]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _139_ (
    .CLK(clk),
    .D(_023_),
    .Q(shift_reg[10]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _140_ (
    .CLK(clk),
    .D(_019_),
    .Q(shift_reg[11]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _141_ (
    .CLK(clk),
    .D(_017_),
    .Q(shift_reg[12]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _142_ (
    .CLK(clk),
    .D(_016_),
    .Q(shift_reg[13]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _143_ (
    .CLK(clk),
    .D(_020_),
    .Q(shift_reg[14]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _144_ (
    .CLK(clk),
    .D(_021_),
    .Q(load_active),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _145_ (
    .CLK(clk),
    .D(_007_),
    .Q(wr_addr[0]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _146_ (
    .CLK(clk),
    .D(_006_),
    .Q(wr_addr[1]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _147_ (
    .CLK(clk),
    .D(_005_),
    .Q(wr_addr[2]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _148_ (
    .CLK(clk),
    .D(_015_),
    .Q(wr_addr[3]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _149_ (
    .CLK(clk),
    .D(_014_),
    .Q(wr_addr[4]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _150_ (
    .CLK(clk),
    .D(_009_),
    .Q(wr_addr[5]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _151_ (
    .CLK(clk),
    .D(_008_),
    .Q(wr_addr[6]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _152_ (
    .CLK(clk),
    .D(_022_),
    .Q(wr_addr[7]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _153_ (
    .CLK(clk),
    .D(1'h1),
    .Q(started),
    .RESET_B(rst_n)
  );
  RM_IHPSG13_1P_256x16_c2_bm_bist u_sram (
    .A_ADDR(mem_addr),
    .A_BIST_ADDR(8'h00),
    .A_BIST_BM(16'h0000),
    .A_BIST_CLK(1'h0),
    .A_BIST_DIN(16'h0000),
    .A_BIST_EN(1'h0),
    .A_BIST_MEN(1'h0),
    .A_BIST_REN(1'h0),
    .A_BIST_WEN(1'h0),
    .A_BM(16'hffff),
    .A_CLK(clk),
    .A_DIN({ shift_reg, serial_in }),
    .A_DLY(1'h1),
    .A_DOUT(instr_word),
    .A_MEN(mem_men),
    .A_REN(mem_ren),
    .A_WEN(mem_wen)
  );
  assign load_word = { shift_reg, serial_in };
  assign run_phase = run_phase_r;
endmodule
