/* Generated by Yosys 0.67+post (git sha1 b8e7da6f40ae8f552c116bf6c359b07c6533e159, Release, GNU /usr/bin/c++ 13.3.0) */

module protocol_core(clk, rst_n, run_phase, instr_word, fetch_addr, port_ui_in, port_uio_in, port_uo_out, port_uio_out);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input run_phase;
  wire run_phase;
  input [15:0] instr_word;
  wire [15:0] instr_word;
  output [7:0] fetch_addr;
  wire [7:0] fetch_addr;
  input [7:0] port_ui_in;
  wire [7:0] port_ui_in;
  input [7:0] port_uio_in;
  wire [7:0] port_uio_in;
  output [7:0] port_uo_out;
  wire [7:0] port_uo_out;
  output [7:0] port_uio_out;
  wire [7:0] port_uio_out;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire fetch_valid;
  wire flag_z;
  wire halted;
  wire [7:0] imm8;
  wire [7:0] next_addr;
  wire [3:0] opcode;
  wire [7:0] pc;
  wire [1:0] rd;
  wire [7:0] \regs[0] ;
  wire [7:0] \regs[1] ;
  wire [7:0] \regs[2] ;
  wire [7:0] \regs[3] ;
  wire [1:0] rs;
  wire shf_left;
  wire [7:0] wait_cnt;
  wire waiting;
  sg13cmos5l_inv_1 _393_ (
    .A(wait_cnt[0]),
    .Y(_059_)
  );
  sg13cmos5l_inv_1 _394_ (
    .A(wait_cnt[6]),
    .Y(_060_)
  );
  sg13cmos5l_inv_1 _395_ (
    .A(instr_word[8]),
    .Y(_061_)
  );
  sg13cmos5l_inv_1 _396_ (
    .A(instr_word[14]),
    .Y(_062_)
  );
  sg13cmos5l_inv_1 _397_ (
    .A(port_ui_in[2]),
    .Y(_063_)
  );
  sg13cmos5l_inv_1 _398_ (
    .A(pc[1]),
    .Y(_064_)
  );
  sg13cmos5l_inv_1 _399_ (
    .A(pc[0]),
    .Y(_065_)
  );
  sg13cmos5l_inv_1 _400_ (
    .A(pc[2]),
    .Y(_066_)
  );
  sg13cmos5l_inv_1 _401_ (
    .A(pc[3]),
    .Y(_067_)
  );
  sg13cmos5l_inv_1 _402_ (
    .A(flag_z),
    .Y(_068_)
  );
  sg13cmos5l_inv_1 _403_ (
    .A(pc[7]),
    .Y(_069_)
  );
  sg13cmos5l_nand2_1 _404_ (
    .A(run_phase),
    .B(fetch_valid),
    .Y(_070_)
  );
  sg13cmos5l_or2_1 _405_ (
    .A(halted),
    .B(_070_),
    .X(_071_)
  );
  sg13cmos5l_nand3_1 _406_ (
    .A(pc[6]),
    .B(run_phase),
    .C(fetch_valid),
    .Y(_072_)
  );
  sg13cmos5l_nor4_1 _407_ (
    .A(instr_word[2]),
    .B(instr_word[1]),
    .C(instr_word[0]),
    .D(instr_word[7]),
    .Y(_073_)
  );
  sg13cmos5l_nor4_1 _408_ (
    .A(instr_word[6]),
    .B(instr_word[5]),
    .C(instr_word[4]),
    .D(instr_word[3]),
    .Y(_074_)
  );
  sg13cmos5l_nand2b_1 _409_ (
    .A_N(instr_word[14]),
    .B(instr_word[15]),
    .Y(_075_)
  );
  sg13cmos5l_nand4_1 _410_ (
    .A(_062_),
    .B(instr_word[15]),
    .C(instr_word[12]),
    .D(instr_word[13]),
    .Y(_076_)
  );
  sg13cmos5l_a21oi_1 _411_ (
    .A1(_073_),
    .A2(_074_),
    .B1(_076_),
    .Y(_077_)
  );
  sg13cmos5l_nor2_1 _412_ (
    .A(waiting),
    .B(_077_),
    .Y(_078_)
  );
  sg13cmos5l_nand2_1 _413_ (
    .A(instr_word[12]),
    .B(_068_),
    .Y(_079_)
  );
  sg13cmos5l_nand3_1 _414_ (
    .A(instr_word[14]),
    .B(instr_word[15]),
    .C(flag_z),
    .Y(_080_)
  );
  sg13cmos5l_nand3_1 _415_ (
    .A(instr_word[14]),
    .B(instr_word[15]),
    .C(_079_),
    .Y(_081_)
  );
  sg13cmos5l_nand3_1 _416_ (
    .A(instr_word[14]),
    .B(instr_word[15]),
    .C(instr_word[13]),
    .Y(_082_)
  );
  sg13cmos5l_nand3_1 _417_ (
    .A(_078_),
    .B(_081_),
    .C(_082_),
    .Y(_083_)
  );
  sg13cmos5l_nor3_1 _418_ (
    .A(wait_cnt[4]),
    .B(wait_cnt[5]),
    .C(wait_cnt[6]),
    .Y(_084_)
  );
  sg13cmos5l_nor2b_1 _419_ (
    .A(wait_cnt[7]),
    .B_N(waiting),
    .Y(_085_)
  );
  sg13cmos5l_nor4_1 _420_ (
    .A(_059_),
    .B(wait_cnt[1]),
    .C(wait_cnt[2]),
    .D(wait_cnt[3]),
    .Y(_086_)
  );
  sg13cmos5l_and3_1 _421_ (
    .A(_084_),
    .B(_085_),
    .C(_086_),
    .X(_087_)
  );
  sg13cmos5l_nand2b_1 _422_ (
    .A_N(instr_word[12]),
    .B(instr_word[13]),
    .Y(_088_)
  );
  sg13cmos5l_nor3_1 _423_ (
    .A(waiting),
    .B(_080_),
    .C(_088_),
    .Y(_089_)
  );
  sg13cmos5l_nor2_1 _424_ (
    .A(_087_),
    .B(_089_),
    .Y(_090_)
  );
  sg13cmos5l_nand2_1 _425_ (
    .A(_083_),
    .B(_090_),
    .Y(_091_)
  );
  sg13cmos5l_nor3_1 _426_ (
    .A(_064_),
    .B(_065_),
    .C(_066_),
    .Y(_092_)
  );
  sg13cmos5l_and2_1 _427_ (
    .A(pc[3]),
    .B(_092_),
    .X(_093_)
  );
  sg13cmos5l_nand2_1 _428_ (
    .A(pc[4]),
    .B(_093_),
    .Y(_094_)
  );
  sg13cmos5l_nand4_1 _429_ (
    .A(pc[4]),
    .B(pc[5]),
    .C(pc[6]),
    .D(_093_),
    .Y(_095_)
  );
  sg13cmos5l_nand4_1 _430_ (
    .A(instr_word[14]),
    .B(instr_word[15]),
    .C(instr_word[12]),
    .D(instr_word[13]),
    .Y(_096_)
  );
  sg13cmos5l_a21oi_1 _431_ (
    .A1(_078_),
    .A2(_096_),
    .B1(_087_),
    .Y(_097_)
  );
  sg13cmos5l_a21o_1 _432_ (
    .A1(_091_),
    .A2(_095_),
    .B1(_097_),
    .X(_098_)
  );
  sg13cmos5l_and4_1 _433_ (
    .A(pc[4]),
    .B(pc[5]),
    .C(_091_),
    .D(_093_),
    .X(_099_)
  );
  sg13cmos5l_o21ai_1 _434_ (
    .A1(pc[6]),
    .A2(_099_),
    .B1(_098_),
    .Y(_100_)
  );
  sg13cmos5l_a21oi_1 _435_ (
    .A1(instr_word[13]),
    .A2(flag_z),
    .B1(_081_),
    .Y(_101_)
  );
  sg13cmos5l_nor2b_1 _436_ (
    .A(waiting),
    .B_N(instr_word[6]),
    .Y(_102_)
  );
  sg13cmos5l_a21oi_1 _437_ (
    .A1(_101_),
    .A2(_102_),
    .B1(halted),
    .Y(_103_)
  );
  sg13cmos5l_a22oi_1 _438_ (
    .A1(_071_),
    .A2(_072_),
    .B1(_100_),
    .B2(_103_),
    .Y(fetch_addr[6])
  );
  sg13cmos5l_or2_1 _439_ (
    .A(halted),
    .B(_097_),
    .X(_104_)
  );
  sg13cmos5l_nand4_1 _440_ (
    .A(pc[5]),
    .B(run_phase),
    .C(fetch_valid),
    .D(_104_),
    .Y(_105_)
  );
  sg13cmos5l_nor2b_1 _441_ (
    .A(waiting),
    .B_N(instr_word[5]),
    .Y(_106_)
  );
  sg13cmos5l_xnor2_1 _442_ (
    .A(pc[5]),
    .B(_094_),
    .Y(_107_)
  );
  sg13cmos5l_a22oi_1 _443_ (
    .A1(_101_),
    .A2(_106_),
    .B1(_107_),
    .B2(_091_),
    .Y(_108_)
  );
  sg13cmos5l_o21ai_1 _444_ (
    .A1(_071_),
    .A2(_108_),
    .B1(_105_),
    .Y(fetch_addr[5])
  );
  sg13cmos5l_nand3_1 _445_ (
    .A(pc[4]),
    .B(run_phase),
    .C(fetch_valid),
    .Y(_109_)
  );
  sg13cmos5l_nor2b_1 _446_ (
    .A(waiting),
    .B_N(instr_word[4]),
    .Y(_110_)
  );
  sg13cmos5l_xor2_1 _447_ (
    .A(pc[4]),
    .B(_093_),
    .X(_111_)
  );
  sg13cmos5l_a22oi_1 _448_ (
    .A1(_101_),
    .A2(_110_),
    .B1(_111_),
    .B2(_091_),
    .Y(_112_)
  );
  sg13cmos5l_a21oi_1 _449_ (
    .A1(pc[4]),
    .A2(_097_),
    .B1(halted),
    .Y(_113_)
  );
  sg13cmos5l_a22oi_1 _450_ (
    .A1(_071_),
    .A2(_109_),
    .B1(_112_),
    .B2(_113_),
    .Y(fetch_addr[4])
  );
  sg13cmos5l_nor2b_1 _451_ (
    .A(waiting),
    .B_N(instr_word[3]),
    .Y(_114_)
  );
  sg13cmos5l_nand2_1 _452_ (
    .A(pc[3]),
    .B(_097_),
    .Y(_115_)
  );
  sg13cmos5l_xnor2_1 _453_ (
    .A(_067_),
    .B(_092_),
    .Y(_116_)
  );
  sg13cmos5l_a221oi_1 _454_ (
    .A1(_101_),
    .A2(_114_),
    .B1(_116_),
    .B2(_091_),
    .C1(halted),
    .Y(_117_)
  );
  sg13cmos5l_a221oi_1 _455_ (
    .A1(_067_),
    .A2(halted),
    .B1(_115_),
    .B2(_117_),
    .C1(_070_),
    .Y(fetch_addr[3])
  );
  sg13cmos5l_a21oi_1 _456_ (
    .A1(pc[1]),
    .A2(pc[0]),
    .B1(pc[2]),
    .Y(_118_)
  );
  sg13cmos5l_nor2_1 _457_ (
    .A(_092_),
    .B(_118_),
    .Y(_119_)
  );
  sg13cmos5l_nand2_1 _458_ (
    .A(_091_),
    .B(_119_),
    .Y(_120_)
  );
  sg13cmos5l_nor2b_1 _459_ (
    .A(waiting),
    .B_N(instr_word[2]),
    .Y(_121_)
  );
  sg13cmos5l_a221oi_1 _460_ (
    .A1(pc[2]),
    .A2(_097_),
    .B1(_101_),
    .B2(_121_),
    .C1(halted),
    .Y(_122_)
  );
  sg13cmos5l_a221oi_1 _461_ (
    .A1(_066_),
    .A2(halted),
    .B1(_120_),
    .B2(_122_),
    .C1(_070_),
    .Y(fetch_addr[2])
  );
  sg13cmos5l_o21ai_1 _462_ (
    .A1(pc[1]),
    .A2(pc[0]),
    .B1(_091_),
    .Y(_123_)
  );
  sg13cmos5l_a21o_1 _463_ (
    .A1(pc[1]),
    .A2(pc[0]),
    .B1(_123_),
    .X(_124_)
  );
  sg13cmos5l_nor2b_1 _464_ (
    .A(waiting),
    .B_N(instr_word[1]),
    .Y(_125_)
  );
  sg13cmos5l_a221oi_1 _465_ (
    .A1(pc[1]),
    .A2(_097_),
    .B1(_101_),
    .B2(_125_),
    .C1(halted),
    .Y(_126_)
  );
  sg13cmos5l_a221oi_1 _466_ (
    .A1(_064_),
    .A2(halted),
    .B1(_124_),
    .B2(_126_),
    .C1(_070_),
    .Y(fetch_addr[1])
  );
  sg13cmos5l_nor2b_1 _467_ (
    .A(waiting),
    .B_N(instr_word[0]),
    .Y(_127_)
  );
  sg13cmos5l_a22oi_1 _468_ (
    .A1(_065_),
    .A2(_091_),
    .B1(_101_),
    .B2(_127_),
    .Y(_128_)
  );
  sg13cmos5l_a21oi_1 _469_ (
    .A1(pc[0]),
    .A2(_097_),
    .B1(halted),
    .Y(_129_)
  );
  sg13cmos5l_a221oi_1 _470_ (
    .A1(_065_),
    .A2(halted),
    .B1(_128_),
    .B2(_129_),
    .C1(_070_),
    .Y(fetch_addr[0])
  );
  sg13cmos5l_nor2b_1 _471_ (
    .A(waiting),
    .B_N(instr_word[7]),
    .Y(_130_)
  );
  sg13cmos5l_nand2_1 _472_ (
    .A(pc[7]),
    .B(_098_),
    .Y(_131_)
  );
  sg13cmos5l_nor2_1 _473_ (
    .A(pc[7]),
    .B(_095_),
    .Y(_132_)
  );
  sg13cmos5l_a221oi_1 _474_ (
    .A1(_101_),
    .A2(_130_),
    .B1(_132_),
    .B2(_091_),
    .C1(halted),
    .Y(_133_)
  );
  sg13cmos5l_a221oi_1 _475_ (
    .A1(halted),
    .A2(_069_),
    .B1(_131_),
    .B2(_133_),
    .C1(_070_),
    .Y(fetch_addr[7])
  );
  sg13cmos5l_nor2_1 _476_ (
    .A(waiting),
    .B(_071_),
    .Y(_134_)
  );
  sg13cmos5l_nor4_1 _477_ (
    .A(waiting),
    .B(_071_),
    .C(_075_),
    .D(_088_),
    .Y(_135_)
  );
  sg13cmos5l_nand3_1 _478_ (
    .A(instr_word[8]),
    .B(instr_word[9]),
    .C(_135_),
    .Y(_136_)
  );
  sg13cmos5l_mux4_1 _479_ (
    .A0(\regs[0] [7]),
    .A1(\regs[2] [7]),
    .A2(\regs[1] [7]),
    .A3(\regs[3] [7]),
    .S0(instr_word[11]),
    .S1(instr_word[10]),
    .X(_137_)
  );
  sg13cmos5l_mux2_1 _480_ (
    .A0(_137_),
    .A1(port_uio_out[7]),
    .S(_136_),
    .X(_000_)
  );
  sg13cmos5l_nor2_1 _481_ (
    .A(instr_word[13]),
    .B(_075_),
    .Y(_138_)
  );
  sg13cmos5l_nand2b_1 _482_ (
    .A_N(instr_word[13]),
    .B(instr_word[12]),
    .Y(_139_)
  );
  sg13cmos5l_nand2_1 _483_ (
    .A(instr_word[12]),
    .B(_138_),
    .Y(_140_)
  );
  sg13cmos5l_nand3_1 _484_ (
    .A(instr_word[9]),
    .B(instr_word[12]),
    .C(_138_),
    .Y(_141_)
  );
  sg13cmos5l_nor2_1 _485_ (
    .A(_062_),
    .B(instr_word[15]),
    .Y(_142_)
  );
  sg13cmos5l_nand2b_1 _486_ (
    .A_N(instr_word[15]),
    .B(instr_word[14]),
    .Y(_143_)
  );
  sg13cmos5l_nand2b_1 _487_ (
    .A_N(instr_word[15]),
    .B(instr_word[13]),
    .Y(_144_)
  );
  sg13cmos5l_nand2_1 _488_ (
    .A(_143_),
    .B(_144_),
    .Y(_145_)
  );
  sg13cmos5l_nor2_1 _489_ (
    .A(_138_),
    .B(_145_),
    .Y(_146_)
  );
  sg13cmos5l_o21ai_1 _490_ (
    .A1(instr_word[15]),
    .A2(_139_),
    .B1(_146_),
    .Y(_147_)
  );
  sg13cmos5l_nand3_1 _491_ (
    .A(_134_),
    .B(_141_),
    .C(_147_),
    .Y(_148_)
  );
  sg13cmos5l_inv_1 _492_ (
    .A(_148_),
    .Y(_149_)
  );
  sg13cmos5l_or3_1 _493_ (
    .A(instr_word[10]),
    .B(instr_word[11]),
    .C(_148_),
    .X(_150_)
  );
  sg13cmos5l_mux4_1 _494_ (
    .A0(\regs[0] [2]),
    .A1(\regs[2] [2]),
    .A2(\regs[1] [2]),
    .A3(\regs[3] [2]),
    .S0(instr_word[11]),
    .S1(instr_word[10]),
    .X(_151_)
  );
  sg13cmos5l_nor2_1 _495_ (
    .A(instr_word[8]),
    .B(instr_word[9]),
    .Y(_152_)
  );
  sg13cmos5l_or2_1 _496_ (
    .A(instr_word[8]),
    .B(instr_word[9]),
    .X(_153_)
  );
  sg13cmos5l_mux4_1 _497_ (
    .A0(\regs[0] [2]),
    .A1(\regs[2] [2]),
    .A2(\regs[1] [2]),
    .A3(\regs[3] [2]),
    .S0(instr_word[9]),
    .S1(instr_word[8]),
    .X(_154_)
  );
  sg13cmos5l_or2_1 _498_ (
    .A(_151_),
    .B(_154_),
    .X(_155_)
  );
  sg13cmos5l_and2_1 _499_ (
    .A(_151_),
    .B(_154_),
    .X(_156_)
  );
  sg13cmos5l_xor2_1 _500_ (
    .A(_151_),
    .B(_154_),
    .X(_157_)
  );
  sg13cmos5l_inv_1 _501_ (
    .A(_157_),
    .Y(_158_)
  );
  sg13cmos5l_mux4_1 _502_ (
    .A0(\regs[0] [1]),
    .A1(\regs[1] [1]),
    .A2(\regs[2] [1]),
    .A3(\regs[3] [1]),
    .S0(instr_word[10]),
    .S1(instr_word[11]),
    .X(_159_)
  );
  sg13cmos5l_mux4_1 _503_ (
    .A0(\regs[0] [1]),
    .A1(\regs[1] [1]),
    .A2(\regs[2] [1]),
    .A3(\regs[3] [1]),
    .S0(instr_word[8]),
    .S1(instr_word[9]),
    .X(_160_)
  );
  sg13cmos5l_nand2b_1 _504_ (
    .A_N(_160_),
    .B(_159_),
    .Y(_161_)
  );
  sg13cmos5l_mux4_1 _505_ (
    .A0(\regs[0] [0]),
    .A1(\regs[2] [0]),
    .A2(\regs[1] [0]),
    .A3(\regs[3] [0]),
    .S0(instr_word[11]),
    .S1(instr_word[10]),
    .X(_162_)
  );
  sg13cmos5l_mux4_1 _506_ (
    .A0(\regs[0] [0]),
    .A1(\regs[2] [0]),
    .A2(\regs[1] [0]),
    .A3(\regs[3] [0]),
    .S0(instr_word[9]),
    .S1(instr_word[8]),
    .X(_163_)
  );
  sg13cmos5l_nor2b_1 _507_ (
    .A(_162_),
    .B_N(_163_),
    .Y(_164_)
  );
  sg13cmos5l_or2_1 _508_ (
    .A(_159_),
    .B(_160_),
    .X(_165_)
  );
  sg13cmos5l_nand2_1 _509_ (
    .A(_159_),
    .B(_160_),
    .Y(_166_)
  );
  sg13cmos5l_xor2_1 _510_ (
    .A(_159_),
    .B(_160_),
    .X(_167_)
  );
  sg13cmos5l_o21ai_1 _511_ (
    .A1(_164_),
    .A2(_167_),
    .B1(_161_),
    .Y(_168_)
  );
  sg13cmos5l_or3_1 _512_ (
    .A(instr_word[12]),
    .B(instr_word[13]),
    .C(_143_),
    .X(_169_)
  );
  sg13cmos5l_a21oi_1 _513_ (
    .A1(_158_),
    .A2(_168_),
    .B1(_169_),
    .Y(_170_)
  );
  sg13cmos5l_o21ai_1 _514_ (
    .A1(_158_),
    .A2(_168_),
    .B1(_170_),
    .Y(_171_)
  );
  sg13cmos5l_nor2_1 _515_ (
    .A(instr_word[14]),
    .B(_144_),
    .Y(_172_)
  );
  sg13cmos5l_and2_1 _516_ (
    .A(instr_word[12]),
    .B(_172_),
    .X(_173_)
  );
  sg13cmos5l_nand2_1 _517_ (
    .A(instr_word[12]),
    .B(_172_),
    .Y(_174_)
  );
  sg13cmos5l_nand2_1 _518_ (
    .A(_162_),
    .B(_163_),
    .Y(_175_)
  );
  sg13cmos5l_a22oi_1 _519_ (
    .A1(_159_),
    .A2(_160_),
    .B1(_162_),
    .B2(_163_),
    .Y(_176_)
  );
  sg13cmos5l_nand2_1 _520_ (
    .A(_166_),
    .B(_175_),
    .Y(_177_)
  );
  sg13cmos5l_nand2_1 _521_ (
    .A(_165_),
    .B(_177_),
    .Y(_178_)
  );
  sg13cmos5l_nor2_1 _522_ (
    .A(_158_),
    .B(_178_),
    .Y(_179_)
  );
  sg13cmos5l_nand3b_1 _523_ (
    .A_N(_176_),
    .B(_157_),
    .C(_165_),
    .Y(_180_)
  );
  sg13cmos5l_xnor2_1 _524_ (
    .A(_157_),
    .B(_178_),
    .Y(_181_)
  );
  sg13cmos5l_nor2_1 _525_ (
    .A(_088_),
    .B(_143_),
    .Y(_182_)
  );
  sg13cmos5l_and3_1 _526_ (
    .A(instr_word[12]),
    .B(instr_word[13]),
    .C(_142_),
    .X(_183_)
  );
  sg13cmos5l_nand3_1 _527_ (
    .A(instr_word[12]),
    .B(instr_word[13]),
    .C(_142_),
    .Y(_184_)
  );
  sg13cmos5l_nor2_1 _528_ (
    .A(_139_),
    .B(_143_),
    .Y(_185_)
  );
  sg13cmos5l_or2_1 _529_ (
    .A(_139_),
    .B(_143_),
    .X(_186_)
  );
  sg13cmos5l_nor3_1 _530_ (
    .A(instr_word[14]),
    .B(instr_word[12]),
    .C(_144_),
    .Y(_187_)
  );
  sg13cmos5l_nor4_1 _531_ (
    .A(_061_),
    .B(instr_word[12]),
    .C(instr_word[13]),
    .D(_075_),
    .Y(_188_)
  );
  sg13cmos5l_a22oi_1 _532_ (
    .A1(_154_),
    .A2(_187_),
    .B1(_188_),
    .B2(_159_),
    .Y(_189_)
  );
  sg13cmos5l_mux4_1 _533_ (
    .A0(\regs[0] [3]),
    .A1(\regs[2] [3]),
    .A2(\regs[1] [3]),
    .A3(\regs[3] [3]),
    .S0(instr_word[11]),
    .S1(instr_word[10]),
    .X(_190_)
  );
  sg13cmos5l_inv_1 _534_ (
    .A(_190_),
    .Y(_191_)
  );
  sg13cmos5l_nor4_1 _535_ (
    .A(instr_word[8]),
    .B(instr_word[12]),
    .C(instr_word[13]),
    .D(_075_),
    .Y(_192_)
  );
  sg13cmos5l_a21oi_1 _536_ (
    .A1(_063_),
    .A2(_152_),
    .B1(_140_),
    .Y(_193_)
  );
  sg13cmos5l_o21ai_1 _537_ (
    .A1(port_uio_in[2]),
    .A2(_152_),
    .B1(_193_),
    .Y(_194_)
  );
  sg13cmos5l_a22oi_1 _538_ (
    .A1(instr_word[2]),
    .A2(_146_),
    .B1(_190_),
    .B2(_192_),
    .Y(_195_)
  );
  sg13cmos5l_a22oi_1 _539_ (
    .A1(_155_),
    .A2(_182_),
    .B1(_185_),
    .B2(_156_),
    .Y(_196_)
  );
  sg13cmos5l_nand4_1 _540_ (
    .A(_189_),
    .B(_194_),
    .C(_195_),
    .D(_196_),
    .Y(_197_)
  );
  sg13cmos5l_a221oi_1 _541_ (
    .A1(_173_),
    .A2(_181_),
    .B1(_183_),
    .B2(_157_),
    .C1(_197_),
    .Y(_198_)
  );
  sg13cmos5l_nand2_1 _542_ (
    .A(_171_),
    .B(_198_),
    .Y(_199_)
  );
  sg13cmos5l_mux2_1 _543_ (
    .A0(_199_),
    .A1(\regs[0] [2]),
    .S(_150_),
    .X(_001_)
  );
  sg13cmos5l_o21ai_1 _544_ (
    .A1(_142_),
    .A2(_173_),
    .B1(_134_),
    .Y(_200_)
  );
  sg13cmos5l_mux4_1 _545_ (
    .A0(\regs[0] [7]),
    .A1(\regs[2] [7]),
    .A2(\regs[1] [7]),
    .A3(\regs[3] [7]),
    .S0(instr_word[9]),
    .S1(instr_word[8]),
    .X(_201_)
  );
  sg13cmos5l_nor2_1 _546_ (
    .A(_137_),
    .B(_201_),
    .Y(_202_)
  );
  sg13cmos5l_nand2_1 _547_ (
    .A(_137_),
    .B(_201_),
    .Y(_203_)
  );
  sg13cmos5l_nor2b_1 _548_ (
    .A(_202_),
    .B_N(_203_),
    .Y(_204_)
  );
  sg13cmos5l_mux4_1 _549_ (
    .A0(\regs[0] [6]),
    .A1(\regs[2] [6]),
    .A2(\regs[1] [6]),
    .A3(\regs[3] [6]),
    .S0(instr_word[11]),
    .S1(instr_word[10]),
    .X(_205_)
  );
  sg13cmos5l_mux4_1 _550_ (
    .A0(\regs[0] [6]),
    .A1(\regs[2] [6]),
    .A2(\regs[1] [6]),
    .A3(\regs[3] [6]),
    .S0(instr_word[9]),
    .S1(instr_word[8]),
    .X(_206_)
  );
  sg13cmos5l_nand2_1 _551_ (
    .A(_205_),
    .B(_206_),
    .Y(_207_)
  );
  sg13cmos5l_nor2_1 _552_ (
    .A(_205_),
    .B(_206_),
    .Y(_208_)
  );
  sg13cmos5l_xnor2_1 _553_ (
    .A(_205_),
    .B(_206_),
    .Y(_209_)
  );
  sg13cmos5l_inv_1 _554_ (
    .A(_209_),
    .Y(_210_)
  );
  sg13cmos5l_mux4_1 _555_ (
    .A0(\regs[0] [5]),
    .A1(\regs[2] [5]),
    .A2(\regs[1] [5]),
    .A3(\regs[3] [5]),
    .S0(instr_word[11]),
    .S1(instr_word[10]),
    .X(_211_)
  );
  sg13cmos5l_mux4_1 _556_ (
    .A0(\regs[0] [5]),
    .A1(\regs[2] [5]),
    .A2(\regs[1] [5]),
    .A3(\regs[3] [5]),
    .S0(instr_word[9]),
    .S1(instr_word[8]),
    .X(_212_)
  );
  sg13cmos5l_or2_1 _557_ (
    .A(_211_),
    .B(_212_),
    .X(_213_)
  );
  sg13cmos5l_mux4_1 _558_ (
    .A0(\regs[0] [4]),
    .A1(\regs[2] [4]),
    .A2(\regs[1] [4]),
    .A3(\regs[3] [4]),
    .S0(instr_word[11]),
    .S1(instr_word[10]),
    .X(_214_)
  );
  sg13cmos5l_mux4_1 _559_ (
    .A0(\regs[0] [4]),
    .A1(\regs[2] [4]),
    .A2(\regs[1] [4]),
    .A3(\regs[3] [4]),
    .S0(instr_word[9]),
    .S1(instr_word[8]),
    .X(_215_)
  );
  sg13cmos5l_nor2_1 _560_ (
    .A(_214_),
    .B(_215_),
    .Y(_216_)
  );
  sg13cmos5l_nand2_1 _561_ (
    .A(_214_),
    .B(_215_),
    .Y(_217_)
  );
  sg13cmos5l_nand2b_1 _562_ (
    .A_N(_216_),
    .B(_217_),
    .Y(_218_)
  );
  sg13cmos5l_mux4_1 _563_ (
    .A0(\regs[0] [3]),
    .A1(\regs[2] [3]),
    .A2(\regs[1] [3]),
    .A3(\regs[3] [3]),
    .S0(instr_word[9]),
    .S1(instr_word[8]),
    .X(_219_)
  );
  sg13cmos5l_inv_1 _564_ (
    .A(_219_),
    .Y(_220_)
  );
  sg13cmos5l_nand2_1 _565_ (
    .A(_191_),
    .B(_220_),
    .Y(_221_)
  );
  sg13cmos5l_nand2_1 _566_ (
    .A(_190_),
    .B(_219_),
    .Y(_222_)
  );
  sg13cmos5l_nor2b_1 _567_ (
    .A(_156_),
    .B_N(_222_),
    .Y(_223_)
  );
  sg13cmos5l_nand2b_1 _568_ (
    .A_N(_156_),
    .B(_222_),
    .Y(_224_)
  );
  sg13cmos5l_o21ai_1 _569_ (
    .A1(_179_),
    .A2(_224_),
    .B1(_221_),
    .Y(_225_)
  );
  sg13cmos5l_a221oi_1 _570_ (
    .A1(_191_),
    .A2(_220_),
    .B1(_223_),
    .B2(_180_),
    .C1(_218_),
    .Y(_226_)
  );
  sg13cmos5l_nand2_1 _571_ (
    .A(_211_),
    .B(_212_),
    .Y(_227_)
  );
  sg13cmos5l_nand2_1 _572_ (
    .A(_217_),
    .B(_227_),
    .Y(_228_)
  );
  sg13cmos5l_o21ai_1 _573_ (
    .A1(_226_),
    .A2(_228_),
    .B1(_213_),
    .Y(_229_)
  );
  sg13cmos5l_o21ai_1 _574_ (
    .A1(_209_),
    .A2(_229_),
    .B1(_207_),
    .Y(_230_)
  );
  sg13cmos5l_xnor2_1 _575_ (
    .A(_204_),
    .B(_230_),
    .Y(_231_)
  );
  sg13cmos5l_xnor2_1 _576_ (
    .A(_209_),
    .B(_229_),
    .Y(_232_)
  );
  sg13cmos5l_and2_1 _577_ (
    .A(_213_),
    .B(_227_),
    .X(_233_)
  );
  sg13cmos5l_o21ai_1 _578_ (
    .A1(_218_),
    .A2(_225_),
    .B1(_217_),
    .Y(_234_)
  );
  sg13cmos5l_xor2_1 _579_ (
    .A(_233_),
    .B(_234_),
    .X(_235_)
  );
  sg13cmos5l_xor2_1 _580_ (
    .A(_218_),
    .B(_225_),
    .X(_236_)
  );
  sg13cmos5l_and2_1 _581_ (
    .A(_221_),
    .B(_222_),
    .X(_237_)
  );
  sg13cmos5l_nor2_1 _582_ (
    .A(_156_),
    .B(_179_),
    .Y(_238_)
  );
  sg13cmos5l_xnor2_1 _583_ (
    .A(_237_),
    .B(_238_),
    .Y(_239_)
  );
  sg13cmos5l_xnor2_1 _584_ (
    .A(_167_),
    .B(_175_),
    .Y(_240_)
  );
  sg13cmos5l_or2_1 _585_ (
    .A(_162_),
    .B(_163_),
    .X(_241_)
  );
  sg13cmos5l_and2_1 _586_ (
    .A(_175_),
    .B(_241_),
    .X(_242_)
  );
  sg13cmos5l_or4_1 _587_ (
    .A(_142_),
    .B(_181_),
    .C(_240_),
    .D(_242_),
    .X(_243_)
  );
  sg13cmos5l_nor4_1 _588_ (
    .A(_235_),
    .B(_236_),
    .C(_239_),
    .D(_243_),
    .Y(_244_)
  );
  sg13cmos5l_nand3_1 _589_ (
    .A(_231_),
    .B(_232_),
    .C(_244_),
    .Y(_245_)
  );
  sg13cmos5l_a21oi_1 _590_ (
    .A1(_169_),
    .A2(_184_),
    .B1(_167_),
    .Y(_246_)
  );
  sg13cmos5l_nor4_1 _591_ (
    .A(_157_),
    .B(_204_),
    .C(_233_),
    .D(_237_),
    .Y(_247_)
  );
  sg13cmos5l_nand3_1 _592_ (
    .A(_218_),
    .B(_246_),
    .C(_247_),
    .Y(_248_)
  );
  sg13cmos5l_nor3_1 _593_ (
    .A(_210_),
    .B(_242_),
    .C(_248_),
    .Y(_249_)
  );
  sg13cmos5l_nand3_1 _594_ (
    .A(_185_),
    .B(_203_),
    .C(_207_),
    .Y(_250_)
  );
  sg13cmos5l_nor4_1 _595_ (
    .A(_177_),
    .B(_224_),
    .C(_228_),
    .D(_250_),
    .Y(_251_)
  );
  sg13cmos5l_nor3_1 _596_ (
    .A(_165_),
    .B(_213_),
    .C(_221_),
    .Y(_252_)
  );
  sg13cmos5l_nand2_1 _597_ (
    .A(_202_),
    .B(_208_),
    .Y(_253_)
  );
  sg13cmos5l_nor3_1 _598_ (
    .A(_155_),
    .B(_241_),
    .C(_253_),
    .Y(_254_)
  );
  sg13cmos5l_and4_1 _599_ (
    .A(_182_),
    .B(_216_),
    .C(_252_),
    .D(_254_),
    .X(_255_)
  );
  sg13cmos5l_nor4_1 _600_ (
    .A(_200_),
    .B(_249_),
    .C(_251_),
    .D(_255_),
    .Y(_256_)
  );
  sg13cmos5l_a22oi_1 _601_ (
    .A1(_068_),
    .A2(_200_),
    .B1(_245_),
    .B2(_256_),
    .Y(_002_)
  );
  sg13cmos5l_xnor2_1 _602_ (
    .A(_164_),
    .B(_167_),
    .Y(_257_)
  );
  sg13cmos5l_nor2_1 _603_ (
    .A(_166_),
    .B(_186_),
    .Y(_258_)
  );
  sg13cmos5l_a21oi_1 _604_ (
    .A1(_165_),
    .A2(_182_),
    .B1(_258_),
    .Y(_259_)
  );
  sg13cmos5l_nor2_1 _605_ (
    .A(port_ui_in[1]),
    .B(_153_),
    .Y(_260_)
  );
  sg13cmos5l_nor2_1 _606_ (
    .A(port_uio_in[1]),
    .B(_152_),
    .Y(_261_)
  );
  sg13cmos5l_nor3_1 _607_ (
    .A(_140_),
    .B(_260_),
    .C(_261_),
    .Y(_262_)
  );
  sg13cmos5l_a221oi_1 _608_ (
    .A1(instr_word[1]),
    .A2(_146_),
    .B1(_151_),
    .B2(_192_),
    .C1(_262_),
    .Y(_263_)
  );
  sg13cmos5l_a22oi_1 _609_ (
    .A1(_160_),
    .A2(_187_),
    .B1(_188_),
    .B2(_162_),
    .Y(_264_)
  );
  sg13cmos5l_nand3_1 _610_ (
    .A(_259_),
    .B(_263_),
    .C(_264_),
    .Y(_265_)
  );
  sg13cmos5l_a221oi_1 _611_ (
    .A1(_167_),
    .A2(_183_),
    .B1(_240_),
    .B2(_173_),
    .C1(_265_),
    .Y(_266_)
  );
  sg13cmos5l_o21ai_1 _612_ (
    .A1(_169_),
    .A2(_257_),
    .B1(_266_),
    .Y(_267_)
  );
  sg13cmos5l_mux2_1 _613_ (
    .A0(_267_),
    .A1(\regs[0] [1]),
    .S(_150_),
    .X(_003_)
  );
  sg13cmos5l_nand3b_1 _614_ (
    .A_N(instr_word[10]),
    .B(instr_word[11]),
    .C(_149_),
    .Y(_268_)
  );
  sg13cmos5l_nand2b_1 _615_ (
    .A_N(_212_),
    .B(_211_),
    .Y(_269_)
  );
  sg13cmos5l_nand2b_1 _616_ (
    .A_N(_215_),
    .B(_214_),
    .Y(_270_)
  );
  sg13cmos5l_inv_1 _617_ (
    .A(_270_),
    .Y(_271_)
  );
  sg13cmos5l_nand2_1 _618_ (
    .A(_190_),
    .B(_220_),
    .Y(_272_)
  );
  sg13cmos5l_nor2b_1 _619_ (
    .A(_154_),
    .B_N(_151_),
    .Y(_273_)
  );
  sg13cmos5l_a21oi_1 _620_ (
    .A1(_158_),
    .A2(_168_),
    .B1(_273_),
    .Y(_274_)
  );
  sg13cmos5l_or2_1 _621_ (
    .A(_237_),
    .B(_274_),
    .X(_275_)
  );
  sg13cmos5l_o21ai_1 _622_ (
    .A1(_237_),
    .A2(_274_),
    .B1(_272_),
    .Y(_276_)
  );
  sg13cmos5l_a21oi_1 _623_ (
    .A1(_218_),
    .A2(_276_),
    .B1(_271_),
    .Y(_277_)
  );
  sg13cmos5l_o21ai_1 _624_ (
    .A1(_233_),
    .A2(_277_),
    .B1(_269_),
    .Y(_278_)
  );
  sg13cmos5l_nor2b_1 _625_ (
    .A(_206_),
    .B_N(_205_),
    .Y(_279_)
  );
  sg13cmos5l_a21oi_1 _626_ (
    .A1(_209_),
    .A2(_278_),
    .B1(_279_),
    .Y(_280_)
  );
  sg13cmos5l_xnor2_1 _627_ (
    .A(_204_),
    .B(_280_),
    .Y(_281_)
  );
  sg13cmos5l_nand2_1 _628_ (
    .A(instr_word[7]),
    .B(_146_),
    .Y(_282_)
  );
  sg13cmos5l_nor2_1 _629_ (
    .A(port_uio_in[7]),
    .B(_152_),
    .Y(_283_)
  );
  sg13cmos5l_nor2_1 _630_ (
    .A(port_ui_in[7]),
    .B(_153_),
    .Y(_284_)
  );
  sg13cmos5l_nor3_1 _631_ (
    .A(_140_),
    .B(_283_),
    .C(_284_),
    .Y(_285_)
  );
  sg13cmos5l_a21oi_1 _632_ (
    .A1(_187_),
    .A2(_201_),
    .B1(_182_),
    .Y(_286_)
  );
  sg13cmos5l_a21oi_1 _633_ (
    .A1(_188_),
    .A2(_205_),
    .B1(_285_),
    .Y(_287_)
  );
  sg13cmos5l_o21ai_1 _634_ (
    .A1(_202_),
    .A2(_286_),
    .B1(_282_),
    .Y(_288_)
  );
  sg13cmos5l_o21ai_1 _635_ (
    .A1(_186_),
    .A2(_203_),
    .B1(_287_),
    .Y(_289_)
  );
  sg13cmos5l_a21oi_1 _636_ (
    .A1(_183_),
    .A2(_204_),
    .B1(_289_),
    .Y(_290_)
  );
  sg13cmos5l_o21ai_1 _637_ (
    .A1(_174_),
    .A2(_231_),
    .B1(_290_),
    .Y(_291_)
  );
  sg13cmos5l_nor2_1 _638_ (
    .A(_288_),
    .B(_291_),
    .Y(_292_)
  );
  sg13cmos5l_o21ai_1 _639_ (
    .A1(_169_),
    .A2(_281_),
    .B1(_292_),
    .Y(_293_)
  );
  sg13cmos5l_mux2_1 _640_ (
    .A0(_293_),
    .A1(\regs[2] [7]),
    .S(_268_),
    .X(_004_)
  );
  sg13cmos5l_nand3_1 _641_ (
    .A(_169_),
    .B(_174_),
    .C(_184_),
    .Y(_294_)
  );
  sg13cmos5l_nor2_1 _642_ (
    .A(port_uio_in[0]),
    .B(_152_),
    .Y(_295_)
  );
  sg13cmos5l_nor2_1 _643_ (
    .A(port_ui_in[0]),
    .B(_153_),
    .Y(_296_)
  );
  sg13cmos5l_nor3_1 _644_ (
    .A(_140_),
    .B(_295_),
    .C(_296_),
    .Y(_297_)
  );
  sg13cmos5l_nand2_1 _645_ (
    .A(_182_),
    .B(_241_),
    .Y(_298_)
  );
  sg13cmos5l_a22oi_1 _646_ (
    .A1(instr_word[0]),
    .A2(_146_),
    .B1(_163_),
    .B2(_187_),
    .Y(_299_)
  );
  sg13cmos5l_a21oi_1 _647_ (
    .A1(_159_),
    .A2(_192_),
    .B1(_297_),
    .Y(_300_)
  );
  sg13cmos5l_o21ai_1 _648_ (
    .A1(_175_),
    .A2(_186_),
    .B1(_300_),
    .Y(_301_)
  );
  sg13cmos5l_a21oi_1 _649_ (
    .A1(_242_),
    .A2(_294_),
    .B1(_301_),
    .Y(_302_)
  );
  sg13cmos5l_nand3_1 _650_ (
    .A(_298_),
    .B(_299_),
    .C(_302_),
    .Y(_303_)
  );
  sg13cmos5l_mux2_1 _651_ (
    .A0(_303_),
    .A1(\regs[0] [0]),
    .S(_150_),
    .X(_005_)
  );
  sg13cmos5l_or2_1 _652_ (
    .A(_209_),
    .B(_278_),
    .X(_304_)
  );
  sg13cmos5l_a21oi_1 _653_ (
    .A1(_209_),
    .A2(_278_),
    .B1(_169_),
    .Y(_305_)
  );
  sg13cmos5l_nand2b_1 _654_ (
    .A_N(_208_),
    .B(_182_),
    .Y(_306_)
  );
  sg13cmos5l_o21ai_1 _655_ (
    .A1(_186_),
    .A2(_207_),
    .B1(_306_),
    .Y(_307_)
  );
  sg13cmos5l_a22oi_1 _656_ (
    .A1(_187_),
    .A2(_206_),
    .B1(_211_),
    .B2(_188_),
    .Y(_308_)
  );
  sg13cmos5l_nand2b_1 _657_ (
    .A_N(port_ui_in[6]),
    .B(_152_),
    .Y(_309_)
  );
  sg13cmos5l_o21ai_1 _658_ (
    .A1(port_uio_in[6]),
    .A2(_152_),
    .B1(_309_),
    .Y(_310_)
  );
  sg13cmos5l_o21ai_1 _659_ (
    .A1(_140_),
    .A2(_310_),
    .B1(_308_),
    .Y(_311_)
  );
  sg13cmos5l_a22oi_1 _660_ (
    .A1(instr_word[6]),
    .A2(_146_),
    .B1(_192_),
    .B2(_137_),
    .Y(_312_)
  );
  sg13cmos5l_o21ai_1 _661_ (
    .A1(_184_),
    .A2(_209_),
    .B1(_312_),
    .Y(_313_)
  );
  sg13cmos5l_nor3_1 _662_ (
    .A(_307_),
    .B(_311_),
    .C(_313_),
    .Y(_314_)
  );
  sg13cmos5l_o21ai_1 _663_ (
    .A1(_174_),
    .A2(_232_),
    .B1(_314_),
    .Y(_315_)
  );
  sg13cmos5l_a21o_1 _664_ (
    .A1(_304_),
    .A2(_305_),
    .B1(_315_),
    .X(_316_)
  );
  sg13cmos5l_mux2_1 _665_ (
    .A0(_316_),
    .A1(\regs[0] [6]),
    .S(_150_),
    .X(_006_)
  );
  sg13cmos5l_xnor2_1 _666_ (
    .A(_233_),
    .B(_277_),
    .Y(_317_)
  );
  sg13cmos5l_nor2_1 _667_ (
    .A(_186_),
    .B(_227_),
    .Y(_318_)
  );
  sg13cmos5l_nor2_1 _668_ (
    .A(port_ui_in[5]),
    .B(_153_),
    .Y(_319_)
  );
  sg13cmos5l_nor2_1 _669_ (
    .A(port_uio_in[5]),
    .B(_152_),
    .Y(_320_)
  );
  sg13cmos5l_nor3_1 _670_ (
    .A(_140_),
    .B(_319_),
    .C(_320_),
    .Y(_321_)
  );
  sg13cmos5l_nand2_1 _671_ (
    .A(instr_word[5]),
    .B(_146_),
    .Y(_322_)
  );
  sg13cmos5l_a22oi_1 _672_ (
    .A1(_187_),
    .A2(_212_),
    .B1(_214_),
    .B2(_188_),
    .Y(_323_)
  );
  sg13cmos5l_a21oi_1 _673_ (
    .A1(_182_),
    .A2(_213_),
    .B1(_318_),
    .Y(_324_)
  );
  sg13cmos5l_a221oi_1 _674_ (
    .A1(_192_),
    .A2(_205_),
    .B1(_233_),
    .B2(_183_),
    .C1(_321_),
    .Y(_325_)
  );
  sg13cmos5l_nand4_1 _675_ (
    .A(_322_),
    .B(_323_),
    .C(_324_),
    .D(_325_),
    .Y(_326_)
  );
  sg13cmos5l_a21oi_1 _676_ (
    .A1(_173_),
    .A2(_235_),
    .B1(_326_),
    .Y(_327_)
  );
  sg13cmos5l_o21ai_1 _677_ (
    .A1(_169_),
    .A2(_317_),
    .B1(_327_),
    .Y(_328_)
  );
  sg13cmos5l_mux2_1 _678_ (
    .A0(_328_),
    .A1(\regs[0] [5]),
    .S(_150_),
    .X(_007_)
  );
  sg13cmos5l_mux2_1 _679_ (
    .A0(_316_),
    .A1(\regs[2] [6]),
    .S(_268_),
    .X(_008_)
  );
  sg13cmos5l_mux2_1 _680_ (
    .A0(_328_),
    .A1(\regs[2] [5]),
    .S(_268_),
    .X(_009_)
  );
  sg13cmos5l_nor3_1 _681_ (
    .A(_071_),
    .B(_078_),
    .C(_087_),
    .Y(_329_)
  );
  sg13cmos5l_or3_1 _682_ (
    .A(_071_),
    .B(_078_),
    .C(_087_),
    .X(_330_)
  );
  sg13cmos5l_a21o_1 _683_ (
    .A1(waiting),
    .A2(_071_),
    .B1(_329_),
    .X(_010_)
  );
  sg13cmos5l_nand3_1 _684_ (
    .A(instr_word[10]),
    .B(instr_word[11]),
    .C(_149_),
    .Y(_331_)
  );
  sg13cmos5l_mux2_1 _685_ (
    .A0(_293_),
    .A1(\regs[3] [7]),
    .S(_331_),
    .X(_011_)
  );
  sg13cmos5l_nor2_1 _686_ (
    .A(_218_),
    .B(_276_),
    .Y(_332_)
  );
  sg13cmos5l_a21o_1 _687_ (
    .A1(_218_),
    .A2(_276_),
    .B1(_169_),
    .X(_333_)
  );
  sg13cmos5l_nor2_1 _688_ (
    .A(port_uio_in[4]),
    .B(_152_),
    .Y(_334_)
  );
  sg13cmos5l_nor2_1 _689_ (
    .A(port_ui_in[4]),
    .B(_153_),
    .Y(_335_)
  );
  sg13cmos5l_nor3_1 _690_ (
    .A(_140_),
    .B(_334_),
    .C(_335_),
    .Y(_336_)
  );
  sg13cmos5l_a221oi_1 _691_ (
    .A1(instr_word[4]),
    .A2(_146_),
    .B1(_192_),
    .B2(_211_),
    .C1(_336_),
    .Y(_337_)
  );
  sg13cmos5l_a22oi_1 _692_ (
    .A1(_188_),
    .A2(_190_),
    .B1(_215_),
    .B2(_187_),
    .Y(_338_)
  );
  sg13cmos5l_nand2b_1 _693_ (
    .A_N(_216_),
    .B(_182_),
    .Y(_339_)
  );
  sg13cmos5l_nand3_1 _694_ (
    .A(_185_),
    .B(_214_),
    .C(_215_),
    .Y(_340_)
  );
  sg13cmos5l_and4_1 _695_ (
    .A(_337_),
    .B(_338_),
    .C(_339_),
    .D(_340_),
    .X(_341_)
  );
  sg13cmos5l_o21ai_1 _696_ (
    .A1(_184_),
    .A2(_218_),
    .B1(_341_),
    .Y(_342_)
  );
  sg13cmos5l_a21oi_1 _697_ (
    .A1(_173_),
    .A2(_236_),
    .B1(_342_),
    .Y(_343_)
  );
  sg13cmos5l_o21ai_1 _698_ (
    .A1(_332_),
    .A2(_333_),
    .B1(_343_),
    .Y(_344_)
  );
  sg13cmos5l_mux2_1 _699_ (
    .A0(_344_),
    .A1(\regs[2] [4]),
    .S(_268_),
    .X(_012_)
  );
  sg13cmos5l_nor3_1 _700_ (
    .A(wait_cnt[0]),
    .B(wait_cnt[1]),
    .C(wait_cnt[2]),
    .Y(_345_)
  );
  sg13cmos5l_nor2b_1 _701_ (
    .A(wait_cnt[3]),
    .B_N(_345_),
    .Y(_346_)
  );
  sg13cmos5l_nand2b_1 _702_ (
    .A_N(wait_cnt[4]),
    .B(_346_),
    .Y(_347_)
  );
  sg13cmos5l_nor2_1 _703_ (
    .A(wait_cnt[5]),
    .B(_347_),
    .Y(_348_)
  );
  sg13cmos5l_nand2_1 _704_ (
    .A(_060_),
    .B(_348_),
    .Y(_349_)
  );
  sg13cmos5l_a21oi_1 _705_ (
    .A1(waiting),
    .A2(_349_),
    .B1(_330_),
    .Y(_350_)
  );
  sg13cmos5l_or2_1 _706_ (
    .A(_085_),
    .B(_130_),
    .X(_351_)
  );
  sg13cmos5l_mux2_1 _707_ (
    .A0(wait_cnt[7]),
    .A1(_351_),
    .S(_350_),
    .X(_013_)
  );
  sg13cmos5l_a21oi_1 _708_ (
    .A1(_237_),
    .A2(_274_),
    .B1(_169_),
    .Y(_352_)
  );
  sg13cmos5l_nand2_1 _709_ (
    .A(_183_),
    .B(_237_),
    .Y(_353_)
  );
  sg13cmos5l_a22oi_1 _710_ (
    .A1(_151_),
    .A2(_188_),
    .B1(_192_),
    .B2(_214_),
    .Y(_354_)
  );
  sg13cmos5l_nor2_1 _711_ (
    .A(port_ui_in[3]),
    .B(_153_),
    .Y(_355_)
  );
  sg13cmos5l_nor2_1 _712_ (
    .A(port_uio_in[3]),
    .B(_152_),
    .Y(_356_)
  );
  sg13cmos5l_nor3_1 _713_ (
    .A(_140_),
    .B(_355_),
    .C(_356_),
    .Y(_357_)
  );
  sg13cmos5l_a221oi_1 _714_ (
    .A1(instr_word[3]),
    .A2(_146_),
    .B1(_187_),
    .B2(_219_),
    .C1(_357_),
    .Y(_358_)
  );
  sg13cmos5l_nor2_1 _715_ (
    .A(_186_),
    .B(_222_),
    .Y(_359_)
  );
  sg13cmos5l_a21oi_1 _716_ (
    .A1(_182_),
    .A2(_221_),
    .B1(_359_),
    .Y(_360_)
  );
  sg13cmos5l_nand4_1 _717_ (
    .A(_353_),
    .B(_354_),
    .C(_358_),
    .D(_360_),
    .Y(_361_)
  );
  sg13cmos5l_a221oi_1 _718_ (
    .A1(_173_),
    .A2(_239_),
    .B1(_275_),
    .B2(_352_),
    .C1(_361_),
    .Y(_362_)
  );
  sg13cmos5l_nand2_1 _719_ (
    .A(\regs[2] [3]),
    .B(_268_),
    .Y(_363_)
  );
  sg13cmos5l_o21ai_1 _720_ (
    .A1(_268_),
    .A2(_362_),
    .B1(_363_),
    .Y(_014_)
  );
  sg13cmos5l_mux2_1 _721_ (
    .A0(_199_),
    .A1(\regs[2] [2]),
    .S(_268_),
    .X(_015_)
  );
  sg13cmos5l_nor3_1 _722_ (
    .A(waiting),
    .B(_071_),
    .C(_096_),
    .Y(_364_)
  );
  sg13cmos5l_or2_1 _723_ (
    .A(halted),
    .B(_364_),
    .X(_016_)
  );
  sg13cmos5l_nand3_1 _724_ (
    .A(_061_),
    .B(instr_word[9]),
    .C(_135_),
    .Y(_365_)
  );
  sg13cmos5l_mux2_1 _725_ (
    .A0(_205_),
    .A1(port_uo_out[6]),
    .S(_365_),
    .X(_017_)
  );
  sg13cmos5l_mux2_1 _726_ (
    .A0(_211_),
    .A1(port_uo_out[5]),
    .S(_365_),
    .X(_018_)
  );
  sg13cmos5l_mux2_1 _727_ (
    .A0(_214_),
    .A1(port_uo_out[4]),
    .S(_365_),
    .X(_019_)
  );
  sg13cmos5l_nand2_1 _728_ (
    .A(port_uo_out[3]),
    .B(_365_),
    .Y(_366_)
  );
  sg13cmos5l_o21ai_1 _729_ (
    .A1(_191_),
    .A2(_365_),
    .B1(_366_),
    .Y(_020_)
  );
  sg13cmos5l_mux2_1 _730_ (
    .A0(_151_),
    .A1(port_uo_out[2]),
    .S(_365_),
    .X(_021_)
  );
  sg13cmos5l_mux2_1 _731_ (
    .A0(_159_),
    .A1(port_uo_out[1]),
    .S(_365_),
    .X(_022_)
  );
  sg13cmos5l_mux2_1 _732_ (
    .A0(_162_),
    .A1(port_uo_out[0]),
    .S(_365_),
    .X(_023_)
  );
  sg13cmos5l_mux2_1 _733_ (
    .A0(_267_),
    .A1(\regs[2] [1]),
    .S(_268_),
    .X(_024_)
  );
  sg13cmos5l_mux2_1 _734_ (
    .A0(_303_),
    .A1(\regs[2] [0]),
    .S(_268_),
    .X(_025_)
  );
  sg13cmos5l_mux2_1 _735_ (
    .A0(_205_),
    .A1(port_uio_out[6]),
    .S(_136_),
    .X(_026_)
  );
  sg13cmos5l_mux2_1 _736_ (
    .A0(_211_),
    .A1(port_uio_out[5]),
    .S(_136_),
    .X(_027_)
  );
  sg13cmos5l_mux2_1 _737_ (
    .A0(_214_),
    .A1(port_uio_out[4]),
    .S(_136_),
    .X(_028_)
  );
  sg13cmos5l_nand2_1 _738_ (
    .A(port_uio_out[3]),
    .B(_136_),
    .Y(_367_)
  );
  sg13cmos5l_o21ai_1 _739_ (
    .A1(_136_),
    .A2(_191_),
    .B1(_367_),
    .Y(_029_)
  );
  sg13cmos5l_mux2_1 _740_ (
    .A0(_151_),
    .A1(port_uio_out[2]),
    .S(_136_),
    .X(_030_)
  );
  sg13cmos5l_mux2_1 _741_ (
    .A0(_159_),
    .A1(port_uio_out[1]),
    .S(_136_),
    .X(_031_)
  );
  sg13cmos5l_mux2_1 _742_ (
    .A0(_162_),
    .A1(port_uio_out[0]),
    .S(_136_),
    .X(_032_)
  );
  sg13cmos5l_mux2_1 _743_ (
    .A0(_316_),
    .A1(\regs[3] [6]),
    .S(_331_),
    .X(_033_)
  );
  sg13cmos5l_mux2_1 _744_ (
    .A0(_328_),
    .A1(\regs[3] [5]),
    .S(_331_),
    .X(_034_)
  );
  sg13cmos5l_nand3b_1 _745_ (
    .A_N(instr_word[11]),
    .B(_149_),
    .C(instr_word[10]),
    .Y(_368_)
  );
  sg13cmos5l_mux2_1 _746_ (
    .A0(_316_),
    .A1(\regs[1] [6]),
    .S(_368_),
    .X(_035_)
  );
  sg13cmos5l_mux2_1 _747_ (
    .A0(_328_),
    .A1(\regs[1] [5]),
    .S(_368_),
    .X(_036_)
  );
  sg13cmos5l_mux2_1 _748_ (
    .A0(_344_),
    .A1(\regs[1] [4]),
    .S(_368_),
    .X(_037_)
  );
  sg13cmos5l_nand2_1 _749_ (
    .A(\regs[1] [3]),
    .B(_368_),
    .Y(_369_)
  );
  sg13cmos5l_o21ai_1 _750_ (
    .A1(_362_),
    .A2(_368_),
    .B1(_369_),
    .Y(_038_)
  );
  sg13cmos5l_mux2_1 _751_ (
    .A0(_293_),
    .A1(\regs[0] [7]),
    .S(_150_),
    .X(_039_)
  );
  sg13cmos5l_mux2_1 _752_ (
    .A0(_199_),
    .A1(\regs[1] [2]),
    .S(_368_),
    .X(_040_)
  );
  sg13cmos5l_mux2_1 _753_ (
    .A0(_267_),
    .A1(\regs[1] [1]),
    .S(_368_),
    .X(_041_)
  );
  sg13cmos5l_mux2_1 _754_ (
    .A0(_303_),
    .A1(\regs[1] [0]),
    .S(_368_),
    .X(_042_)
  );
  sg13cmos5l_mux2_1 _755_ (
    .A0(_344_),
    .A1(\regs[3] [4]),
    .S(_331_),
    .X(_043_)
  );
  sg13cmos5l_nand2_1 _756_ (
    .A(\regs[3] [3]),
    .B(_331_),
    .Y(_370_)
  );
  sg13cmos5l_o21ai_1 _757_ (
    .A1(_331_),
    .A2(_362_),
    .B1(_370_),
    .Y(_044_)
  );
  sg13cmos5l_mux2_1 _758_ (
    .A0(_199_),
    .A1(\regs[3] [2]),
    .S(_331_),
    .X(_045_)
  );
  sg13cmos5l_mux2_1 _759_ (
    .A0(_267_),
    .A1(\regs[3] [1]),
    .S(_331_),
    .X(_046_)
  );
  sg13cmos5l_mux2_1 _760_ (
    .A0(_303_),
    .A1(\regs[3] [0]),
    .S(_331_),
    .X(_047_)
  );
  sg13cmos5l_mux2_1 _761_ (
    .A0(_344_),
    .A1(\regs[0] [4]),
    .S(_150_),
    .X(_048_)
  );
  sg13cmos5l_nand2_1 _762_ (
    .A(\regs[0] [3]),
    .B(_150_),
    .Y(_371_)
  );
  sg13cmos5l_o21ai_1 _763_ (
    .A1(_150_),
    .A2(_362_),
    .B1(_371_),
    .Y(_049_)
  );
  sg13cmos5l_xnor2_1 _764_ (
    .A(_060_),
    .B(_348_),
    .Y(_372_)
  );
  sg13cmos5l_nand2_1 _765_ (
    .A(waiting),
    .B(_372_),
    .Y(_373_)
  );
  sg13cmos5l_nor2_1 _766_ (
    .A(_102_),
    .B(_330_),
    .Y(_374_)
  );
  sg13cmos5l_a22oi_1 _767_ (
    .A1(_060_),
    .A2(_330_),
    .B1(_373_),
    .B2(_374_),
    .Y(_050_)
  );
  sg13cmos5l_xnor2_1 _768_ (
    .A(wait_cnt[5]),
    .B(_347_),
    .Y(_375_)
  );
  sg13cmos5l_nand2_1 _769_ (
    .A(wait_cnt[5]),
    .B(_330_),
    .Y(_376_)
  );
  sg13cmos5l_a21oi_1 _770_ (
    .A1(waiting),
    .A2(_375_),
    .B1(_106_),
    .Y(_377_)
  );
  sg13cmos5l_o21ai_1 _771_ (
    .A1(_330_),
    .A2(_377_),
    .B1(_376_),
    .Y(_051_)
  );
  sg13cmos5l_xor2_1 _772_ (
    .A(wait_cnt[4]),
    .B(_346_),
    .X(_378_)
  );
  sg13cmos5l_a21oi_1 _773_ (
    .A1(waiting),
    .A2(_378_),
    .B1(_110_),
    .Y(_379_)
  );
  sg13cmos5l_nor2_1 _774_ (
    .A(wait_cnt[4]),
    .B(_329_),
    .Y(_380_)
  );
  sg13cmos5l_a21oi_1 _775_ (
    .A1(_329_),
    .A2(_379_),
    .B1(_380_),
    .Y(_052_)
  );
  sg13cmos5l_nor2b_1 _776_ (
    .A(_345_),
    .B_N(waiting),
    .Y(_381_)
  );
  sg13cmos5l_o21ai_1 _777_ (
    .A1(_330_),
    .A2(_381_),
    .B1(wait_cnt[3]),
    .Y(_382_)
  );
  sg13cmos5l_a21oi_1 _778_ (
    .A1(waiting),
    .A2(_346_),
    .B1(_114_),
    .Y(_383_)
  );
  sg13cmos5l_o21ai_1 _779_ (
    .A1(_330_),
    .A2(_383_),
    .B1(_382_),
    .Y(_053_)
  );
  sg13cmos5l_o21ai_1 _780_ (
    .A1(wait_cnt[0]),
    .A2(wait_cnt[1]),
    .B1(waiting),
    .Y(_384_)
  );
  sg13cmos5l_nand2_1 _781_ (
    .A(_329_),
    .B(_384_),
    .Y(_385_)
  );
  sg13cmos5l_nand2_1 _782_ (
    .A(wait_cnt[2]),
    .B(_385_),
    .Y(_386_)
  );
  sg13cmos5l_a21oi_1 _783_ (
    .A1(waiting),
    .A2(_345_),
    .B1(_121_),
    .Y(_387_)
  );
  sg13cmos5l_o21ai_1 _784_ (
    .A1(_330_),
    .A2(_387_),
    .B1(_386_),
    .Y(_054_)
  );
  sg13cmos5l_nor2_1 _785_ (
    .A(wait_cnt[1]),
    .B(_329_),
    .Y(_388_)
  );
  sg13cmos5l_xnor2_1 _786_ (
    .A(wait_cnt[0]),
    .B(wait_cnt[1]),
    .Y(_389_)
  );
  sg13cmos5l_a21oi_1 _787_ (
    .A1(waiting),
    .A2(_389_),
    .B1(_125_),
    .Y(_390_)
  );
  sg13cmos5l_a21oi_1 _788_ (
    .A1(_329_),
    .A2(_390_),
    .B1(_388_),
    .Y(_055_)
  );
  sg13cmos5l_a21oi_1 _789_ (
    .A1(_059_),
    .A2(waiting),
    .B1(_127_),
    .Y(_391_)
  );
  sg13cmos5l_nor2_1 _790_ (
    .A(wait_cnt[0]),
    .B(_329_),
    .Y(_392_)
  );
  sg13cmos5l_a21oi_1 _791_ (
    .A1(_329_),
    .A2(_391_),
    .B1(_392_),
    .Y(_056_)
  );
  sg13cmos5l_mux2_1 _792_ (
    .A0(_137_),
    .A1(port_uo_out[7]),
    .S(_365_),
    .X(_057_)
  );
  sg13cmos5l_mux2_1 _793_ (
    .A0(_293_),
    .A1(\regs[1] [7]),
    .S(_368_),
    .X(_058_)
  );
  sg13cmos5l_dfrbpq_1 _794_ (
    .CLK(clk),
    .D(_023_),
    .Q(port_uo_out[0]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _795_ (
    .CLK(clk),
    .D(_022_),
    .Q(port_uo_out[1]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _796_ (
    .CLK(clk),
    .D(_021_),
    .Q(port_uo_out[2]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _797_ (
    .CLK(clk),
    .D(_020_),
    .Q(port_uo_out[3]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _798_ (
    .CLK(clk),
    .D(_019_),
    .Q(port_uo_out[4]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _799_ (
    .CLK(clk),
    .D(_018_),
    .Q(port_uo_out[5]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _800_ (
    .CLK(clk),
    .D(_017_),
    .Q(port_uo_out[6]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _801_ (
    .CLK(clk),
    .D(_057_),
    .Q(port_uo_out[7]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _802_ (
    .CLK(clk),
    .D(_042_),
    .Q(\regs[1] [0]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _803_ (
    .CLK(clk),
    .D(_041_),
    .Q(\regs[1] [1]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _804_ (
    .CLK(clk),
    .D(_040_),
    .Q(\regs[1] [2]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _805_ (
    .CLK(clk),
    .D(_038_),
    .Q(\regs[1] [3]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _806_ (
    .CLK(clk),
    .D(_037_),
    .Q(\regs[1] [4]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _807_ (
    .CLK(clk),
    .D(_036_),
    .Q(\regs[1] [5]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _808_ (
    .CLK(clk),
    .D(_035_),
    .Q(\regs[1] [6]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _809_ (
    .CLK(clk),
    .D(_058_),
    .Q(\regs[1] [7]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _810_ (
    .CLK(clk),
    .D(_032_),
    .Q(port_uio_out[0]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _811_ (
    .CLK(clk),
    .D(_031_),
    .Q(port_uio_out[1]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _812_ (
    .CLK(clk),
    .D(_030_),
    .Q(port_uio_out[2]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _813_ (
    .CLK(clk),
    .D(_029_),
    .Q(port_uio_out[3]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _814_ (
    .CLK(clk),
    .D(_028_),
    .Q(port_uio_out[4]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _815_ (
    .CLK(clk),
    .D(_027_),
    .Q(port_uio_out[5]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _816_ (
    .CLK(clk),
    .D(_026_),
    .Q(port_uio_out[6]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _817_ (
    .CLK(clk),
    .D(_000_),
    .Q(port_uio_out[7]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _818_ (
    .CLK(clk),
    .D(_002_),
    .Q(flag_z),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _819_ (
    .CLK(clk),
    .D(_025_),
    .Q(\regs[2] [0]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _820_ (
    .CLK(clk),
    .D(_024_),
    .Q(\regs[2] [1]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _821_ (
    .CLK(clk),
    .D(_015_),
    .Q(\regs[2] [2]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _822_ (
    .CLK(clk),
    .D(_014_),
    .Q(\regs[2] [3]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _823_ (
    .CLK(clk),
    .D(_012_),
    .Q(\regs[2] [4]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _824_ (
    .CLK(clk),
    .D(_009_),
    .Q(\regs[2] [5]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _825_ (
    .CLK(clk),
    .D(_008_),
    .Q(\regs[2] [6]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _826_ (
    .CLK(clk),
    .D(_004_),
    .Q(\regs[2] [7]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _827_ (
    .CLK(clk),
    .D(_010_),
    .Q(waiting),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _828_ (
    .CLK(clk),
    .D(_047_),
    .Q(\regs[3] [0]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _829_ (
    .CLK(clk),
    .D(_046_),
    .Q(\regs[3] [1]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _830_ (
    .CLK(clk),
    .D(_045_),
    .Q(\regs[3] [2]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _831_ (
    .CLK(clk),
    .D(_044_),
    .Q(\regs[3] [3]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _832_ (
    .CLK(clk),
    .D(_043_),
    .Q(\regs[3] [4]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _833_ (
    .CLK(clk),
    .D(_034_),
    .Q(\regs[3] [5]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _834_ (
    .CLK(clk),
    .D(_033_),
    .Q(\regs[3] [6]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _835_ (
    .CLK(clk),
    .D(_011_),
    .Q(\regs[3] [7]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _836_ (
    .CLK(clk),
    .D(_056_),
    .Q(wait_cnt[0]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _837_ (
    .CLK(clk),
    .D(_055_),
    .Q(wait_cnt[1]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _838_ (
    .CLK(clk),
    .D(_054_),
    .Q(wait_cnt[2]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _839_ (
    .CLK(clk),
    .D(_053_),
    .Q(wait_cnt[3]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _840_ (
    .CLK(clk),
    .D(_052_),
    .Q(wait_cnt[4]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _841_ (
    .CLK(clk),
    .D(_051_),
    .Q(wait_cnt[5]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _842_ (
    .CLK(clk),
    .D(_050_),
    .Q(wait_cnt[6]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _843_ (
    .CLK(clk),
    .D(_013_),
    .Q(wait_cnt[7]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _844_ (
    .CLK(clk),
    .D(_016_),
    .Q(halted),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _845_ (
    .CLK(clk),
    .D(_005_),
    .Q(\regs[0] [0]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _846_ (
    .CLK(clk),
    .D(_003_),
    .Q(\regs[0] [1]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _847_ (
    .CLK(clk),
    .D(_001_),
    .Q(\regs[0] [2]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _848_ (
    .CLK(clk),
    .D(_049_),
    .Q(\regs[0] [3]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _849_ (
    .CLK(clk),
    .D(_048_),
    .Q(\regs[0] [4]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _850_ (
    .CLK(clk),
    .D(_007_),
    .Q(\regs[0] [5]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _851_ (
    .CLK(clk),
    .D(_006_),
    .Q(\regs[0] [6]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _852_ (
    .CLK(clk),
    .D(_039_),
    .Q(\regs[0] [7]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _853_ (
    .CLK(clk),
    .D(fetch_addr[0]),
    .Q(pc[0]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _854_ (
    .CLK(clk),
    .D(fetch_addr[1]),
    .Q(pc[1]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _855_ (
    .CLK(clk),
    .D(fetch_addr[2]),
    .Q(pc[2]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _856_ (
    .CLK(clk),
    .D(fetch_addr[3]),
    .Q(pc[3]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _857_ (
    .CLK(clk),
    .D(fetch_addr[4]),
    .Q(pc[4]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _858_ (
    .CLK(clk),
    .D(fetch_addr[5]),
    .Q(pc[5]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _859_ (
    .CLK(clk),
    .D(fetch_addr[6]),
    .Q(pc[6]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _860_ (
    .CLK(clk),
    .D(fetch_addr[7]),
    .Q(pc[7]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _861_ (
    .CLK(clk),
    .D(run_phase),
    .Q(fetch_valid),
    .RESET_B(rst_n)
  );
  assign next_addr = fetch_addr;
  assign shf_left = instr_word[8];
  assign imm8 = instr_word[7:0];
  assign rs = instr_word[9:8];
  assign rd = instr_word[11:10];
  assign opcode = instr_word[15:12];
endmodule

module protocol_program_memory(clk, rst_n, mode_pin, serial_in, fetch_addr, instr_word, run_phase);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input mode_pin;
  wire mode_pin;
  input serial_in;
  wire serial_in;
  input [7:0] fetch_addr;
  wire [7:0] fetch_addr;
  output [15:0] instr_word;
  wire [15:0] instr_word;
  output run_phase;
  wire run_phase;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire [3:0] bit_cnt;
  wire full;
  wire load_active;
  wire [15:0] load_word;
  wire [7:0] mem_addr;
  wire mem_men;
  wire mem_ren;
  wire mem_wen;
  wire run_phase_r;
  wire [14:0] shift_reg;
  wire started;
  wire [7:0] wr_addr;
  sg13cmos5l_inv_1 _056_ (
    .A(load_active),
    .Y(mem_ren)
  );
  sg13cmos5l_inv_1 _057_ (
    .A(wr_addr[2]),
    .Y(_050_)
  );
  sg13cmos5l_inv_1 _058_ (
    .A(wr_addr[7]),
    .Y(_051_)
  );
  sg13cmos5l_mux2_1 _059_ (
    .A0(fetch_addr[6]),
    .A1(wr_addr[6]),
    .S(load_active),
    .X(mem_addr[6])
  );
  sg13cmos5l_mux2_1 _060_ (
    .A0(fetch_addr[5]),
    .A1(wr_addr[5]),
    .S(load_active),
    .X(mem_addr[5])
  );
  sg13cmos5l_mux2_1 _061_ (
    .A0(fetch_addr[4]),
    .A1(wr_addr[4]),
    .S(load_active),
    .X(mem_addr[4])
  );
  sg13cmos5l_mux2_1 _062_ (
    .A0(fetch_addr[3]),
    .A1(wr_addr[3]),
    .S(load_active),
    .X(mem_addr[3])
  );
  sg13cmos5l_nor2_1 _063_ (
    .A(load_active),
    .B(fetch_addr[2]),
    .Y(_052_)
  );
  sg13cmos5l_a21oi_1 _064_ (
    .A1(load_active),
    .A2(_050_),
    .B1(_052_),
    .Y(mem_addr[2])
  );
  sg13cmos5l_mux2_1 _065_ (
    .A0(fetch_addr[1]),
    .A1(wr_addr[1]),
    .S(load_active),
    .X(mem_addr[1])
  );
  sg13cmos5l_mux2_1 _066_ (
    .A0(fetch_addr[0]),
    .A1(wr_addr[0]),
    .S(load_active),
    .X(mem_addr[0])
  );
  sg13cmos5l_nor2_1 _067_ (
    .A(load_active),
    .B(fetch_addr[7]),
    .Y(_053_)
  );
  sg13cmos5l_a21oi_1 _068_ (
    .A1(load_active),
    .A2(_051_),
    .B1(_053_),
    .Y(mem_addr[7])
  );
  sg13cmos5l_nand2_1 _069_ (
    .A(load_active),
    .B(mode_pin),
    .Y(_054_)
  );
  sg13cmos5l_nand4_1 _070_ (
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .C(bit_cnt[2]),
    .D(bit_cnt[3]),
    .Y(_055_)
  );
  sg13cmos5l_nor3_1 _071_ (
    .A(full),
    .B(_054_),
    .C(_055_),
    .Y(mem_wen)
  );
  sg13cmos5l_nand2b_1 _072_ (
    .A_N(mem_wen),
    .B(load_active),
    .Y(mem_men)
  );
  sg13cmos5l_and3_1 _073_ (
    .A(load_active),
    .B(mode_pin),
    .C(started),
    .X(_030_)
  );
  sg13cmos5l_nand3_1 _074_ (
    .A(load_active),
    .B(mode_pin),
    .C(started),
    .Y(_031_)
  );
  sg13cmos5l_mux2_1 _075_ (
    .A0(shift_reg[3]),
    .A1(shift_reg[2]),
    .S(_030_),
    .X(_000_)
  );
  sg13cmos5l_mux2_1 _076_ (
    .A0(shift_reg[2]),
    .A1(shift_reg[1]),
    .S(_030_),
    .X(_001_)
  );
  sg13cmos5l_mux2_1 _077_ (
    .A0(shift_reg[1]),
    .A1(shift_reg[0]),
    .S(_030_),
    .X(_002_)
  );
  sg13cmos5l_mux2_1 _078_ (
    .A0(shift_reg[0]),
    .A1(serial_in),
    .S(_030_),
    .X(_003_)
  );
  sg13cmos5l_nand3_1 _079_ (
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .C(_030_),
    .Y(_032_)
  );
  sg13cmos5l_nand4_1 _080_ (
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .C(bit_cnt[2]),
    .D(_030_),
    .Y(_033_)
  );
  sg13cmos5l_xnor2_1 _081_ (
    .A(bit_cnt[3]),
    .B(_033_),
    .Y(_004_)
  );
  sg13cmos5l_nand3_1 _082_ (
    .A(wr_addr[3]),
    .B(wr_addr[2]),
    .C(wr_addr[1]),
    .Y(_034_)
  );
  sg13cmos5l_nand4_1 _083_ (
    .A(wr_addr[0]),
    .B(wr_addr[6]),
    .C(wr_addr[5]),
    .D(wr_addr[4]),
    .Y(_035_)
  );
  sg13cmos5l_nor2_1 _084_ (
    .A(_034_),
    .B(_035_),
    .Y(_036_)
  );
  sg13cmos5l_or3_1 _085_ (
    .A(_051_),
    .B(_034_),
    .C(_035_),
    .X(_037_)
  );
  sg13cmos5l_nor3_1 _086_ (
    .A(full),
    .B(_055_),
    .C(_031_),
    .Y(_038_)
  );
  sg13cmos5l_nand3_1 _087_ (
    .A(wr_addr[0]),
    .B(_037_),
    .C(_038_),
    .Y(_039_)
  );
  sg13cmos5l_nand4_1 _088_ (
    .A(wr_addr[0]),
    .B(wr_addr[1]),
    .C(_037_),
    .D(_038_),
    .Y(_040_)
  );
  sg13cmos5l_nor2_1 _089_ (
    .A(_050_),
    .B(_040_),
    .Y(_041_)
  );
  sg13cmos5l_xnor2_1 _090_ (
    .A(wr_addr[2]),
    .B(_040_),
    .Y(_005_)
  );
  sg13cmos5l_xnor2_1 _091_ (
    .A(wr_addr[1]),
    .B(_039_),
    .Y(_006_)
  );
  sg13cmos5l_a21o_1 _092_ (
    .A1(_037_),
    .A2(_038_),
    .B1(wr_addr[0]),
    .X(_042_)
  );
  sg13cmos5l_and2_1 _093_ (
    .A(_039_),
    .B(_042_),
    .X(_007_)
  );
  sg13cmos5l_nand3_1 _094_ (
    .A(wr_addr[4]),
    .B(wr_addr[3]),
    .C(_041_),
    .Y(_043_)
  );
  sg13cmos5l_nand4_1 _095_ (
    .A(wr_addr[5]),
    .B(wr_addr[4]),
    .C(wr_addr[3]),
    .D(_041_),
    .Y(_044_)
  );
  sg13cmos5l_xnor2_1 _096_ (
    .A(wr_addr[6]),
    .B(_044_),
    .Y(_008_)
  );
  sg13cmos5l_xnor2_1 _097_ (
    .A(wr_addr[5]),
    .B(_043_),
    .Y(_009_)
  );
  sg13cmos5l_xnor2_1 _098_ (
    .A(bit_cnt[2]),
    .B(_032_),
    .Y(_010_)
  );
  sg13cmos5l_a21o_1 _099_ (
    .A1(bit_cnt[0]),
    .A2(_030_),
    .B1(bit_cnt[1]),
    .X(_045_)
  );
  sg13cmos5l_and2_1 _100_ (
    .A(_032_),
    .B(_045_),
    .X(_011_)
  );
  sg13cmos5l_nor3_1 _101_ (
    .A(_055_),
    .B(_031_),
    .C(_037_),
    .Y(_046_)
  );
  sg13cmos5l_or2_1 _102_ (
    .A(full),
    .B(_046_),
    .X(_012_)
  );
  sg13cmos5l_xnor2_1 _103_ (
    .A(bit_cnt[0]),
    .B(_031_),
    .Y(_013_)
  );
  sg13cmos5l_a21o_1 _104_ (
    .A1(wr_addr[3]),
    .A2(_041_),
    .B1(wr_addr[4]),
    .X(_047_)
  );
  sg13cmos5l_and2_1 _105_ (
    .A(_043_),
    .B(_047_),
    .X(_014_)
  );
  sg13cmos5l_xor2_1 _106_ (
    .A(wr_addr[3]),
    .B(_041_),
    .X(_015_)
  );
  sg13cmos5l_mux2_1 _107_ (
    .A0(shift_reg[13]),
    .A1(shift_reg[12]),
    .S(_030_),
    .X(_016_)
  );
  sg13cmos5l_mux2_1 _108_ (
    .A0(shift_reg[12]),
    .A1(shift_reg[11]),
    .S(_030_),
    .X(_017_)
  );
  sg13cmos5l_a21oi_1 _109_ (
    .A1(mem_ren),
    .A2(started),
    .B1(mode_pin),
    .Y(_048_)
  );
  sg13cmos5l_or2_1 _110_ (
    .A(run_phase_r),
    .B(_048_),
    .X(_018_)
  );
  sg13cmos5l_mux2_1 _111_ (
    .A0(shift_reg[11]),
    .A1(shift_reg[10]),
    .S(_030_),
    .X(_019_)
  );
  sg13cmos5l_mux2_1 _112_ (
    .A0(shift_reg[13]),
    .A1(shift_reg[14]),
    .S(_031_),
    .X(_020_)
  );
  sg13cmos5l_nor2_1 _113_ (
    .A(load_active),
    .B(mode_pin),
    .Y(_049_)
  );
  sg13cmos5l_a21oi_1 _114_ (
    .A1(started),
    .A2(_054_),
    .B1(_049_),
    .Y(_021_)
  );
  sg13cmos5l_a21o_1 _115_ (
    .A1(_036_),
    .A2(_038_),
    .B1(wr_addr[7]),
    .X(_022_)
  );
  sg13cmos5l_mux2_1 _116_ (
    .A0(shift_reg[10]),
    .A1(shift_reg[9]),
    .S(_030_),
    .X(_023_)
  );
  sg13cmos5l_mux2_1 _117_ (
    .A0(shift_reg[9]),
    .A1(shift_reg[8]),
    .S(_030_),
    .X(_024_)
  );
  sg13cmos5l_mux2_1 _118_ (
    .A0(shift_reg[8]),
    .A1(shift_reg[7]),
    .S(_030_),
    .X(_025_)
  );
  sg13cmos5l_mux2_1 _119_ (
    .A0(shift_reg[7]),
    .A1(shift_reg[6]),
    .S(_030_),
    .X(_026_)
  );
  sg13cmos5l_mux2_1 _120_ (
    .A0(shift_reg[6]),
    .A1(shift_reg[5]),
    .S(_030_),
    .X(_027_)
  );
  sg13cmos5l_mux2_1 _121_ (
    .A0(shift_reg[5]),
    .A1(shift_reg[4]),
    .S(_030_),
    .X(_028_)
  );
  sg13cmos5l_mux2_1 _122_ (
    .A0(shift_reg[3]),
    .A1(shift_reg[4]),
    .S(_031_),
    .X(_029_)
  );
  sg13cmos5l_dfrbpq_1 _123_ (
    .CLK(clk),
    .D(_018_),
    .Q(run_phase_r),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _124_ (
    .CLK(clk),
    .D(_013_),
    .Q(bit_cnt[0]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _125_ (
    .CLK(clk),
    .D(_011_),
    .Q(bit_cnt[1]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _126_ (
    .CLK(clk),
    .D(_010_),
    .Q(bit_cnt[2]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _127_ (
    .CLK(clk),
    .D(_004_),
    .Q(bit_cnt[3]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _128_ (
    .CLK(clk),
    .D(_012_),
    .Q(full),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _129_ (
    .CLK(clk),
    .D(_003_),
    .Q(shift_reg[0]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _130_ (
    .CLK(clk),
    .D(_002_),
    .Q(shift_reg[1]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _131_ (
    .CLK(clk),
    .D(_001_),
    .Q(shift_reg[2]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _132_ (
    .CLK(clk),
    .D(_000_),
    .Q(shift_reg[3]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _133_ (
    .CLK(clk),
    .D(_029_),
    .Q(shift_reg[4]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _134_ (
    .CLK(clk),
    .D(_028_),
    .Q(shift_reg[5]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _135_ (
    .CLK(clk),
    .D(_027_),
    .Q(shift_reg[6]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _136_ (
    .CLK(clk),
    .D(_026_),
    .Q(shift_reg[7]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _137_ (
    .CLK(clk),
    .D(_025_),
    .Q(shift_reg[8]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _138_ (
    .CLK(clk),
    .D(_024_),
    .Q(shift_reg[9]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _139_ (
    .CLK(clk),
    .D(_023_),
    .Q(shift_reg[10]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _140_ (
    .CLK(clk),
    .D(_019_),
    .Q(shift_reg[11]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _141_ (
    .CLK(clk),
    .D(_017_),
    .Q(shift_reg[12]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _142_ (
    .CLK(clk),
    .D(_016_),
    .Q(shift_reg[13]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _143_ (
    .CLK(clk),
    .D(_020_),
    .Q(shift_reg[14]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _144_ (
    .CLK(clk),
    .D(_021_),
    .Q(load_active),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _145_ (
    .CLK(clk),
    .D(_007_),
    .Q(wr_addr[0]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _146_ (
    .CLK(clk),
    .D(_006_),
    .Q(wr_addr[1]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _147_ (
    .CLK(clk),
    .D(_005_),
    .Q(wr_addr[2]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _148_ (
    .CLK(clk),
    .D(_015_),
    .Q(wr_addr[3]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _149_ (
    .CLK(clk),
    .D(_014_),
    .Q(wr_addr[4]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _150_ (
    .CLK(clk),
    .D(_009_),
    .Q(wr_addr[5]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _151_ (
    .CLK(clk),
    .D(_008_),
    .Q(wr_addr[6]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _152_ (
    .CLK(clk),
    .D(_022_),
    .Q(wr_addr[7]),
    .RESET_B(rst_n)
  );
  sg13cmos5l_dfrbpq_1 _153_ (
    .CLK(clk),
    .D(1'h1),
    .Q(started),
    .RESET_B(rst_n)
  );
  RM_IHPSG13_1P_256x16_c2_bm_bist u_sram (
    .A_ADDR(mem_addr),
    .A_BIST_ADDR(8'h00),
    .A_BIST_BM(16'h0000),
    .A_BIST_CLK(1'h0),
    .A_BIST_DIN(16'h0000),
    .A_BIST_EN(1'h0),
    .A_BIST_MEN(1'h0),
    .A_BIST_REN(1'h0),
    .A_BIST_WEN(1'h0),
    .A_BM(16'hffff),
    .A_CLK(clk),
    .A_DIN({ shift_reg, serial_in }),
    .A_DLY(1'h1),
    .A_DOUT(instr_word),
    .A_MEN(mem_men),
    .A_REN(mem_ren),
    .A_WEN(mem_wen)
  );
  assign load_word = { shift_reg, serial_in };
  assign run_phase = run_phase_r;
endmodule

module tt_um_2amlogic_protocol_emulator(ui_in, uo_out, uio_in, uio_out, uio_oe, ena, clk, rst_n);
  input [7:0] ui_in;
  wire [7:0] ui_in;
  output [7:0] uo_out;
  wire [7:0] uo_out;
  input [7:0] uio_in;
  wire [7:0] uio_in;
  output [7:0] uio_out;
  wire [7:0] uio_out;
  output [7:0] uio_oe;
  wire [7:0] uio_oe;
  input ena;
  wire ena;
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  wire _unused;
  wire [7:0] fetch_addr;
  wire [15:0] instr_word;
  wire run_phase;
  protocol_core u_core (
    .clk(clk),
    .fetch_addr(fetch_addr),
    .instr_word(instr_word),
    .port_ui_in(ui_in),
    .port_uio_in(uio_in),
    .port_uio_out(uio_out),
    .port_uo_out(uo_out),
    .rst_n(rst_n),
    .run_phase(run_phase)
  );
  protocol_program_memory u_prog_mem (
    .clk(clk),
    .fetch_addr(fetch_addr),
    .instr_word(instr_word),
    .mode_pin(ui_in[7]),
    .rst_n(rst_n),
    .run_phase(run_phase),
    .serial_in(ui_in[0])
  );
  assign _unused = 1'h0;
  assign uio_oe = 8'h00;
endmodule
