; i2c_rd_03.asm -- GENERATED by verification/firmware_templates.py
; (issue #93). seed=20261009 protocol=i2c_rd index=3
; params={"address": 8, "grade": "i2c_std", "pointer": 255, "read_byte": 255, "stretch": [{"duration_class": "medium", "extra_cycles": 143, "fall": 19, "hold_cycles": 378, "site": "pre_sr"}, {"duration_class": "long", "extra_cycles": 369, "fall": 29, "hold_cycles": 604, "site": "read_clock"}]}
; Regenerate: python3 verification/firmware_templates.py --seed 20261009 --out DIR
; Body is firmware/tools/gen_i2c_sr.py output (the committed
; i2c_std_sr_poll.asm stream) with only the three LDI R0 (inverted
; address-W / pointer / address-R) immediates changed; comments below
; still name the committed program's 0x50 / 0x5A bytes. The read
; byte and stretch schedule are driven
; by the PERIPHERAL (see i2c_rd_03.schedule.json), not by this source.
; i2c_std_sr_poll.asm -- bit-banged I2C controller, Standard-mode (100 kHz class) phase budget:
; write -> repeated START -> read (issue #92, part of #23). GENERATED by
; firmware/tools/gen_i2c_sr.py -- the four i2c_*_sr*.asm programs share one
; instruction stream and differ only in phase literals and the SCL poll.
;
; Transfer: START, 0xA0 (0x50 W) + ACK, 0x5A + ACK, repeated START, 0xA1
; (0x50 R) + ACK, ONE read byte driven by the peripheral and acknowledged
; by NOTHING (the controller releases SDA on the 9th clock: NACK), STOP.
; The received byte is published on UO_OUT before HALT so the bench can
; check what the core actually shifted in from the bus.
;
; Pin plan (same as i2c_fast.asm / i2c_std.asm): UIO_OUT bit 0 = SCL,
; bit 7 = SDA, writing 1 RELEASES the line. The bench composes the
; wired-AND from uio_out/uio_in (uio_oe is fixed to 0 at the top level;
; DR 0008 / #75 owns the silicon-true open-drain half).
;
; Budgets (cycles): t_LOW 235, t_HIGH 200, t_HD;STA 205, t_SU;STA 235,
; t_SU;STO 205.  t_SU;STA is the span from the SCL rise that precedes the
; repeated START to the OUT that pulls SDA low, i.e. the UM10204 Table 10
; setup time, here paced AT the Table 10 minimum.
; Variant: SCL POLLING. After EVERY SCL rise (data, ACK, repeated START and
; STOP) the program polls the peripheral's SCL level (IN uio_in bit 0) and
; loops while it reads low -- clock stretching (UM10204 section 3.1.9).
; The poll costs 2 extra cycles per rise phase (LDI + IN precede the
; hold) so the hold after the IN that sees SCL high is the full budget: an
; unstretched rise phase is budget+2 cycles, and a stretched one is never
; shorter than the budget. DETERMINISM CLAIM: with the peripheral not
; stretching, every phase is exact and data-independent. When the peripheral
; stretches, the interval spent in a `poll` loop is data-dependent by
; design (it lasts as long as the peripheral holds SCL) and is EXCLUDED from
; the determinism claim; every other phase stays exact. The `BZ poll`
; instructions are the program's only data-dependent branches (DR 0001's
; sanctioned handshake branch; the assembler's lint warns on each, one per
; polled rise, and the bench asserts that exact count).
; The bit loops need a counter, and the ISA has four registers, so the
; loop keeps R0 = ~byte (shifted left; after 8 shifts it is 0, which the
; AND/XOR pin recipe turns into SDA released for the following ACK slot),
; R1 = counter, R2 = scratch (constants are re-LDI'd where needed), R3 =
; the pin value for the next OUT. LDI/MOV/SHF/OUT/BNZ are 1 cycle each
; (taken or not), so the loop-back costs no extra cycle in any phase.
;
; `.cyclesec` convention (same as i2c_fast.asm): a section opens AT the OUT
; that starts a phase and closes before the OUT that ends it, so its
; cycle count IS the phase's measured length.

; ---------------------------------------------------------------- setup
        LDI   R3, 0x81        ; both lines released: bus idle
        OUT   UIO_OUT, R3
        WAIT  255             ; idle bus before the START
        LDI   R3, 0x01        ; SCL high, SDA low
; --------------------------------------------------------------- START
.cyclesec i2c_start_hold
        OUT   UIO_OUT, R3   ; START: SDA falls while SCL high
        LDI   R0, 0xEF       ; ~byte (inverted-data trick)
        LDI   R1, 0x08       ; bit counter
        MOV   R3, R0
        LDI   R2, 0x80
        AND   R3, R2
        XOR   R3, R2         ; R3 = SDA(bit 1), SCL low
        WAIT  197      ; 198 cycles
.endcyclesec
; ------------------------------------------ byte 1: address 0xA0 (0x50 W)
tx1_loop:
.cyclesec i2c_tx1_low
        OUT   UIO_OUT, R3   ; SCL falls, SDA = data bit
        WAIT  231      ; 232 cycles
        LDI   R2, 0x01
        OR    R3, R2         ; raise SCL, SDA unchanged
.endcyclesec
.cyclesec i2c_tx1_high
        OUT   UIO_OUT, R3   ; SCL rises: bit sampled on the line
        LDI   R3, 0x01       ; poll mask
        poll0: IN    R2, UIO_IN   ; peripheral's SCL level
        AND   R2, R3
        BZ    poll0          ; SCL held low -> poll again
        WAIT  188      ; 189 cycles
        SHF   R0, LEFT       ; next bit into position
        MOV   R3, R0
        LDI   R2, 0x80
        AND   R3, R2
        XOR   R3, R2         ; R3 = next SDA, SCL low
        LDI   R2, 0x01
        SUB   R1, R2         ; counter--  (sets Z)
        BNZ   tx1_loop      ; 8 data clocks
.endcyclesec
.cyclesec i2c_ack1_low
        OUT   UIO_OUT, R3   ; 9th clock: SCL falls, SDA released
        LDI   R3, 0x81
        WAIT  232      ; 233 cycles
.endcyclesec
.cyclesec i2c_ack1_high
        OUT   UIO_OUT, R3   ; ACK clock rises (peripheral pulls SDA)
        LDI   R3, 0x01       ; poll mask
        poll1: IN    R2, UIO_IN   ; peripheral's SCL level
        AND   R2, R3
        BZ    poll1          ; SCL held low -> poll again
        LDI   R0, 0x00       ; ~byte (inverted-data trick)
        LDI   R1, 0x08       ; bit counter
        MOV   R3, R0
        LDI   R2, 0x80
        AND   R3, R2
        XOR   R3, R2         ; R3 = SDA(bit 1), SCL low
        WAIT  190      ; 191 cycles
.endcyclesec
; ------------------------------------------ byte 2: payload 0x5A
tx2_loop:
.cyclesec i2c_tx2_low
        OUT   UIO_OUT, R3   ; SCL falls, SDA = data bit
        WAIT  231      ; 232 cycles
        LDI   R2, 0x01
        OR    R3, R2         ; raise SCL, SDA unchanged
.endcyclesec
.cyclesec i2c_tx2_high
        OUT   UIO_OUT, R3   ; SCL rises: bit sampled on the line
        LDI   R3, 0x01       ; poll mask
        poll2: IN    R2, UIO_IN   ; peripheral's SCL level
        AND   R2, R3
        BZ    poll2          ; SCL held low -> poll again
        WAIT  188      ; 189 cycles
        SHF   R0, LEFT       ; next bit into position
        MOV   R3, R0
        LDI   R2, 0x80
        AND   R3, R2
        XOR   R3, R2         ; R3 = next SDA, SCL low
        LDI   R2, 0x01
        SUB   R1, R2         ; counter--  (sets Z)
        BNZ   tx2_loop      ; 8 data clocks
.endcyclesec
.cyclesec i2c_ack2_low
        OUT   UIO_OUT, R3   ; 9th clock: SCL falls, SDA released
        LDI   R3, 0x81
        WAIT  232      ; 233 cycles
.endcyclesec
.cyclesec i2c_ack2_high
        OUT   UIO_OUT, R3   ; ACK clock rises
        LDI   R3, 0x01       ; poll mask
        poll3: IN    R2, UIO_IN   ; peripheral's SCL level
        AND   R2, R3
        BZ    poll3          ; SCL held low -> poll again
        LDI   R3, 0x80       ; SCL low, SDA released (for the Sr)
        WAIT  195      ; 196 cycles
.endcyclesec
; ------------------------------------------------- repeated START
.cyclesec i2c_sr_low
        OUT   UIO_OUT, R3   ; SCL falls, SDA released (high)
        LDI   R3, 0x81
        LDI   R0, 0xEE       ; ~0xA1 for the next byte
        LDI   R1, 0x08
        WAIT  230      ; 231 cycles
.endcyclesec
.cyclesec i2c_sr_rise
        OUT   UIO_OUT, R3   ; SCL rises with SDA high: Sr setup begins
        LDI   R3, 0x01       ; poll mask
        poll4: IN    R2, UIO_IN   ; peripheral's SCL level
        AND   R2, R3
        BZ    poll4          ; SCL held low -> poll again
        LDI   R3, 0x01       ; SCL high, SDA low
        WAIT  230      ; 231 cycles NEGCTL-SUSTA
.endcyclesec
.cyclesec i2c_sr_hold
        OUT   UIO_OUT, R3   ; repeated START: SDA falls while SCL high
        MOV   R3, R0
        LDI   R2, 0x80
        AND   R3, R2
        XOR   R3, R2         ; R3 = SDA(bit 1), SCL low
        WAIT  199      ; 200 cycles
.endcyclesec
; ------------------------------------------ byte 3: address 0xA1 (0x50 R)
tx3_loop:
.cyclesec i2c_tx3_low
        OUT   UIO_OUT, R3   ; SCL falls, SDA = data bit
        WAIT  231      ; 232 cycles
        LDI   R2, 0x01
        OR    R3, R2         ; raise SCL, SDA unchanged
.endcyclesec
.cyclesec i2c_tx3_high
        OUT   UIO_OUT, R3   ; SCL rises: bit sampled on the line
        LDI   R3, 0x01       ; poll mask
        poll5: IN    R2, UIO_IN   ; peripheral's SCL level
        AND   R2, R3
        BZ    poll5          ; SCL held low -> poll again
        WAIT  188      ; 189 cycles
        SHF   R0, LEFT       ; next bit into position
        MOV   R3, R0
        LDI   R2, 0x80
        AND   R3, R2
        XOR   R3, R2         ; R3 = next SDA, SCL low
        LDI   R2, 0x01
        SUB   R1, R2         ; counter--  (sets Z)
        BNZ   tx3_loop      ; 8 data clocks
.endcyclesec
.cyclesec i2c_ack3_low
        OUT   UIO_OUT, R3   ; 9th clock: SCL falls, SDA released
        LDI   R3, 0x81
        WAIT  232      ; 233 cycles
.endcyclesec
.cyclesec i2c_ack3_high
        OUT   UIO_OUT, R3   ; ACK clock rises
        LDI   R3, 0x01       ; poll mask
        poll6: IN    R2, UIO_IN   ; peripheral's SCL level
        AND   R2, R3
        BZ    poll6          ; SCL held low -> poll again
        LDI   R0, 0x00       ; receive accumulator
        LDI   R1, 0x08
        LDI   R3, 0x80       ; SCL low, SDA released
        WAIT  193      ; 194 cycles
.endcyclesec
; ----------------------------------- read byte (peripheral drives SDA)
rd_loop:
.cyclesec i2c_rd_low
        OUT   UIO_OUT, R3   ; SCL falls, SDA released to the peripheral
        LDI   R3, 0x81
        WAIT  232      ; 233 cycles
.endcyclesec
.cyclesec i2c_rd_high
        OUT   UIO_OUT, R3   ; SCL rises: peripheral's bit is on the line
        LDI   R3, 0x01       ; poll mask
        poll7: IN    R2, UIO_IN   ; peripheral's SCL level
        AND   R2, R3
        BZ    poll7          ; SCL held low -> poll again
        IN    R2, UIO_IN     ; sample the bus
        LDI   R3, 0x80       ; mask AND next SCL-low pins
        AND   R2, R3         ; isolate SDA (bit 7)
        SHF   R2, RIGHT
        SHF   R2, RIGHT
        SHF   R2, RIGHT
        SHF   R2, RIGHT
        SHF   R2, RIGHT
        SHF   R2, RIGHT
        SHF   R2, RIGHT      ; bit 7 -> bit 0
        SHF   R0, LEFT
        OR    R0, R2         ; MSB first
        WAIT  181      ; 182 cycles
        LDI   R2, 0x01
        SUB   R1, R2         ; counter--  (sets Z)
        BNZ   rd_loop        ; 8 data clocks
.endcyclesec
.cyclesec i2c_nack_low
        OUT   UIO_OUT, R3   ; 9th clock: SCL falls, SDA stays released
        LDI   R3, 0x81
        WAIT  232      ; 233 cycles
.endcyclesec
.cyclesec i2c_nack_high
        OUT   UIO_OUT, R3   ; SCL rises, SDA released: controller NACK
        LDI   R3, 0x01       ; poll mask
        poll8: IN    R2, UIO_IN   ; peripheral's SCL level
        AND   R2, R3
        BZ    poll8          ; SCL held low -> poll again
        LDI   R3, 0x80
        WAIT  195      ; 196 cycles
.endcyclesec
; ------------------------------------------------------------- STOP
.cyclesec i2c_stop_low
        OUT   UIO_OUT, R3   ; SCL falls, SDA released
        LDI   R3, 0x00       ; SDA low during the low period
        OUT   UIO_OUT, R3
        WAIT  230      ; 231 cycles
        LDI   R3, 0x01       ; SCL high, SDA low
.endcyclesec
.cyclesec i2c_stop_setup
        OUT   UIO_OUT, R3   ; SCL rises: STOP setup begins
        LDI   R3, 0x01       ; poll mask
        poll9: IN    R2, UIO_IN   ; peripheral's SCL level
        AND   R2, R3
        BZ    poll9          ; SCL held low -> poll again
        LDI   R3, 0x81       ; SDA released
        WAIT  200      ; 201 cycles
.endcyclesec
        OUT   UIO_OUT, R3     ; SDA rises while SCL high: STOP
        OUT   UO_OUT, R0      ; publish the received byte
        WAIT  255             ; hold the bus idle
        HALT
