/* Generated by Yosys 0.68 (git sha1 38e001a6f, Release, Clang /workspace/YoWASP/yosys/wasi-sdk-33.0-x86_64-linux/share/cmake/../..//bin/clang++ 22.1.0) */

(* top =  1  *)
(* src = "/home/ubuntu/loom-workspaces/sg13cmos5l-protocol-emulator/.loom/worktrees/issue-2/src/tt_um_2amlogic_protocol_emulator.v:31.1-63.10" *)
module tt_um_2amlogic_protocol_emulator(ui_in, uo_out, uio_in, uio_out, uio_oe, ena, clk, rst_n);
  (* src = "/home/ubuntu/loom-workspaces/sg13cmos5l-protocol-emulator/.loom/worktrees/issue-2/src/tt_um_2amlogic_protocol_emulator.v:32.23-32.28" *)
  input [7:0] ui_in;
  wire [7:0] ui_in;
  (* src = "/home/ubuntu/loom-workspaces/sg13cmos5l-protocol-emulator/.loom/worktrees/issue-2/src/tt_um_2amlogic_protocol_emulator.v:33.23-33.29" *)
  output [7:0] uo_out;
  wire [7:0] uo_out;
  (* src = "/home/ubuntu/loom-workspaces/sg13cmos5l-protocol-emulator/.loom/worktrees/issue-2/src/tt_um_2amlogic_protocol_emulator.v:34.23-34.29" *)
  input [7:0] uio_in;
  wire [7:0] uio_in;
  (* src = "/home/ubuntu/loom-workspaces/sg13cmos5l-protocol-emulator/.loom/worktrees/issue-2/src/tt_um_2amlogic_protocol_emulator.v:35.23-35.30" *)
  output [7:0] uio_out;
  wire [7:0] uio_out;
  (* src = "/home/ubuntu/loom-workspaces/sg13cmos5l-protocol-emulator/.loom/worktrees/issue-2/src/tt_um_2amlogic_protocol_emulator.v:36.23-36.29" *)
  output [7:0] uio_oe;
  wire [7:0] uio_oe;
  (* src = "/home/ubuntu/loom-workspaces/sg13cmos5l-protocol-emulator/.loom/worktrees/issue-2/src/tt_um_2amlogic_protocol_emulator.v:37.23-37.26" *)
  input ena;
  wire ena;
  (* src = "/home/ubuntu/loom-workspaces/sg13cmos5l-protocol-emulator/.loom/worktrees/issue-2/src/tt_um_2amlogic_protocol_emulator.v:38.23-38.26" *)
  input clk;
  wire clk;
  (* src = "/home/ubuntu/loom-workspaces/sg13cmos5l-protocol-emulator/.loom/worktrees/issue-2/src/tt_um_2amlogic_protocol_emulator.v:39.23-39.28" *)
  input rst_n;
  wire rst_n;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "/home/ubuntu/loom-workspaces/sg13cmos5l-protocol-emulator/.loom/worktrees/issue-2/src/tt_um_2amlogic_protocol_emulator.v:61.8-61.15" *)
  wire _unused;
  (* src = "/home/ubuntu/loom-workspaces/sg13cmos5l-protocol-emulator/.loom/worktrees/issue-2/src/tt_um_2amlogic_protocol_emulator.v:42.13-42.19" *)
  wire [7:0] uo_reg;
  sg13cmos5l_mux2_1 _08_ (
    .A0(uo_reg[6]),
    .A1(ui_in[6]),
    .S(ena),
    .X(_04_)
  );
  sg13cmos5l_mux2_1 _09_ (
    .A0(uo_reg[5]),
    .A1(ui_in[5]),
    .S(ena),
    .X(_05_)
  );
  sg13cmos5l_mux2_1 _10_ (
    .A0(uo_reg[4]),
    .A1(ui_in[4]),
    .S(ena),
    .X(_06_)
  );
  sg13cmos5l_mux2_1 _11_ (
    .A0(uo_reg[3]),
    .A1(ui_in[3]),
    .S(ena),
    .X(_07_)
  );
  sg13cmos5l_mux2_1 _12_ (
    .A0(uo_reg[2]),
    .A1(ui_in[2]),
    .S(ena),
    .X(_00_)
  );
  sg13cmos5l_mux2_1 _13_ (
    .A0(uo_reg[1]),
    .A1(ui_in[1]),
    .S(ena),
    .X(_01_)
  );
  sg13cmos5l_mux2_1 _14_ (
    .A0(uo_reg[0]),
    .A1(ui_in[0]),
    .S(ena),
    .X(_02_)
  );
  sg13cmos5l_mux2_1 _15_ (
    .A0(uo_reg[7]),
    .A1(ui_in[7]),
    .S(ena),
    .X(_03_)
  );
  (* src = "/home/ubuntu/loom-workspaces/sg13cmos5l-protocol-emulator/.loom/worktrees/issue-2/src/tt_um_2amlogic_protocol_emulator.v:44.3-50.6" *)
  sg13cmos5l_dfrbpq_1 _16_ (
    .CLK(clk),
    .D(_02_),
    .Q(uo_reg[0]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ubuntu/loom-workspaces/sg13cmos5l-protocol-emulator/.loom/worktrees/issue-2/src/tt_um_2amlogic_protocol_emulator.v:44.3-50.6" *)
  sg13cmos5l_dfrbpq_1 _17_ (
    .CLK(clk),
    .D(_01_),
    .Q(uo_reg[1]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ubuntu/loom-workspaces/sg13cmos5l-protocol-emulator/.loom/worktrees/issue-2/src/tt_um_2amlogic_protocol_emulator.v:44.3-50.6" *)
  sg13cmos5l_dfrbpq_1 _18_ (
    .CLK(clk),
    .D(_00_),
    .Q(uo_reg[2]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ubuntu/loom-workspaces/sg13cmos5l-protocol-emulator/.loom/worktrees/issue-2/src/tt_um_2amlogic_protocol_emulator.v:44.3-50.6" *)
  sg13cmos5l_dfrbpq_1 _19_ (
    .CLK(clk),
    .D(_07_),
    .Q(uo_reg[3]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ubuntu/loom-workspaces/sg13cmos5l-protocol-emulator/.loom/worktrees/issue-2/src/tt_um_2amlogic_protocol_emulator.v:44.3-50.6" *)
  sg13cmos5l_dfrbpq_1 _20_ (
    .CLK(clk),
    .D(_06_),
    .Q(uo_reg[4]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ubuntu/loom-workspaces/sg13cmos5l-protocol-emulator/.loom/worktrees/issue-2/src/tt_um_2amlogic_protocol_emulator.v:44.3-50.6" *)
  sg13cmos5l_dfrbpq_1 _21_ (
    .CLK(clk),
    .D(_05_),
    .Q(uo_reg[5]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ubuntu/loom-workspaces/sg13cmos5l-protocol-emulator/.loom/worktrees/issue-2/src/tt_um_2amlogic_protocol_emulator.v:44.3-50.6" *)
  sg13cmos5l_dfrbpq_1 _22_ (
    .CLK(clk),
    .D(_04_),
    .Q(uo_reg[6]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ubuntu/loom-workspaces/sg13cmos5l-protocol-emulator/.loom/worktrees/issue-2/src/tt_um_2amlogic_protocol_emulator.v:44.3-50.6" *)
  sg13cmos5l_dfrbpq_1 _23_ (
    .CLK(clk),
    .D(_03_),
    .Q(uo_reg[7]),
    .RESET_B(rst_n)
  );
  assign _unused = 1'h0;
  assign uio_oe = 8'h00;
  assign uio_out = 8'h00;
  assign uo_out = uo_reg;
endmodule
