; uart_11.asm -- GENERATED by verification/firmware_templates.py
; (issue #93). seed=20261009 protocol=uart index=11
; params={"payloads": [93, 168], "period": 100}
; Regenerate: python3 verification/firmware_templates.py --seed 20261009 --out DIR
        LDI   R1, 1
        OUT   UO_OUT, R1       ; TX idles HIGH
        WAIT  255              ; idle before the first start bit
; ---- frame 1: 0x5D
        LDI   R0, 0x5D
        LDI   R3, 8
        LDI   R2, 0
        OUT   UO_OUT, R2       ; START
        WAIT  96
f1_bit:
.cyclesec uart_bit_frame1
        MOV   R2, R0
        AND   R2, R1
        OUT   UO_OUT, R2       ; data bit
        SHF   R0, RIGHT
        SUB   R3, R1
        WAIT  93
        BNZ   f1_bit
.endcyclesec
        WAIT  1
        OUT   UO_OUT, R1       ; STOP
        WAIT  255
; ---- frame 2: 0xA8
        LDI   R0, 0xA8
        LDI   R3, 8
        LDI   R2, 0
        OUT   UO_OUT, R2       ; START
        WAIT  96
f2_bit:
.cyclesec uart_bit_frame2
        MOV   R2, R0
        AND   R2, R1
        OUT   UO_OUT, R2       ; data bit
        SHF   R0, RIGHT
        SUB   R3, R1
        WAIT  93
        BNZ   f2_bit
.endcyclesec
        WAIT  1
        OUT   UO_OUT, R1       ; STOP
        WAIT  255
        HALT
