; spi_18.asm -- GENERATED by verification/firmware_templates.py
; (issue #93). seed=20261009 protocol=spi index=18
; params={"cpha": 0, "cpol": 1, "half_period": 2, "miso": [233], "mode": 2, "mosi": [0]}
; Regenerate: python3 verification/firmware_templates.py --seed 20261009 --out DIR
        LDI   R2, 0x03      ; CS released, SCLK idle
        OUT   UO_OUT, R2
        WAIT  15
; ---- burst 0: MOSI 0x00
        LDI   R2, 0x02      ; CS asserted
        OUT   UO_OUT, R2
        WAIT  3
        LDI   R1, 0x02
        LDI   R2, 0x00
.cyclesec spi_rand_b0
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        OUT   UO_OUT, R1
        LDI   R2, 0x00
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        OUT   UO_OUT, R1
        LDI   R2, 0x00
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        OUT   UO_OUT, R1
        LDI   R2, 0x00
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        OUT   UO_OUT, R1
        LDI   R2, 0x00
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        OUT   UO_OUT, R1
        LDI   R2, 0x00
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        OUT   UO_OUT, R1
        LDI   R2, 0x00
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        OUT   UO_OUT, R1
        LDI   R2, 0x00
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        OUT   UO_OUT, R1
        LDI   R2, 0x00
.endcyclesec
        WAIT  3
        LDI   R2, 0x03      ; CS released
        OUT   UO_OUT, R2
        WAIT  31
        HALT
