; spi_16.asm -- GENERATED by verification/firmware_templates.py
; (issue #93). seed=20261009 protocol=spi index=16
; params={"cpha": 0, "cpol": 0, "half_period": 3, "miso": [164], "mode": 0, "mosi": [0]}
; Regenerate: python3 verification/firmware_templates.py --seed 20261009 --out DIR
        LDI   R2, 0x01      ; CS released, SCLK idle
        OUT   UO_OUT, R2
        WAIT  15
; ---- burst 0: MOSI 0x00
        LDI   R2, 0x00      ; CS asserted
        OUT   UO_OUT, R2
        WAIT  3
        LDI   R1, 0x00
        LDI   R2, 0x02
.cyclesec spi_rand_b0
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        WAIT  0
        OUT   UO_OUT, R1
        LDI   R2, 0x02
        WAIT  0
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        WAIT  0
        OUT   UO_OUT, R1
        LDI   R2, 0x02
        WAIT  0
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        WAIT  0
        OUT   UO_OUT, R1
        LDI   R2, 0x02
        WAIT  0
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        WAIT  0
        OUT   UO_OUT, R1
        LDI   R2, 0x02
        WAIT  0
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        WAIT  0
        OUT   UO_OUT, R1
        LDI   R2, 0x02
        WAIT  0
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        WAIT  0
        OUT   UO_OUT, R1
        LDI   R2, 0x02
        WAIT  0
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        WAIT  0
        OUT   UO_OUT, R1
        LDI   R2, 0x02
        WAIT  0
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        WAIT  0
        OUT   UO_OUT, R1
        LDI   R2, 0x00
        WAIT  0
.endcyclesec
        WAIT  3
        LDI   R2, 0x01      ; CS released
        OUT   UO_OUT, R2
        WAIT  31
        HALT
