; spi_03.asm -- GENERATED by verification/firmware_templates.py
; (issue #93). seed=20261009 protocol=spi index=3
; params={"cpha": 1, "cpol": 1, "half_period": 2, "miso": [88], "mode": 3, "mosi": [0]}
; Regenerate: python3 verification/firmware_templates.py --seed 20261009 --out DIR
        LDI   R2, 0x09      ; CS released, SCLK idle
        OUT   UIO_OUT, R2      ; idle image before the drivers are on
        LDI   R3, 0x0B      ; CS|MOSI|SCLK
        WCTL  UIO_DIR, R3      ; DR 0012: push-pull
        WAIT  13
; ---- burst 0: MOSI 0x00
        LDI   R2, 0x08      ; CS asserted
        OUT   UIO_OUT, R2
        WAIT  3
        LDI   R1, 0x00
        LDI   R2, 0x08
.cyclesec spi_rand_b0
        OUT   UIO_OUT, R1
        IN    R3, UIO_IN
        OUT   UIO_OUT, R2
        LDI   R2, 0x08
        OUT   UIO_OUT, R1
        IN    R3, UIO_IN
        OUT   UIO_OUT, R2
        LDI   R2, 0x08
        OUT   UIO_OUT, R1
        IN    R3, UIO_IN
        OUT   UIO_OUT, R2
        LDI   R2, 0x08
        OUT   UIO_OUT, R1
        IN    R3, UIO_IN
        OUT   UIO_OUT, R2
        LDI   R2, 0x08
        OUT   UIO_OUT, R1
        IN    R3, UIO_IN
        OUT   UIO_OUT, R2
        LDI   R2, 0x08
        OUT   UIO_OUT, R1
        IN    R3, UIO_IN
        OUT   UIO_OUT, R2
        LDI   R2, 0x08
        OUT   UIO_OUT, R1
        IN    R3, UIO_IN
        OUT   UIO_OUT, R2
        LDI   R2, 0x08
        OUT   UIO_OUT, R1
        IN    R3, UIO_IN
        OUT   UIO_OUT, R2
        LDI   R2, 0x00
.endcyclesec
        WAIT  3
        LDI   R2, 0x09      ; CS released
        OUT   UIO_OUT, R2
        WAIT  31
        HALT
