#!/usr/bin/env python3
"""Generator for the four `i2c_*_sr*.asm` programs (issue #92, part of #23).

The committed `.asm` files under `firmware/asm/` are the evidence (DR 0003);
this script is how they were written, kept so the Fast/Standard pair and the
polling/non-polling variants provably share one instruction stream and differ
only in phase literals. It does not run in the verification flow.

    python3 firmware/tools/gen_i2c_sr.py            # (re)write the four files
    python3 firmware/tools/gen_i2c_sr.py --check    # exit 1 on drift

Every phase is a span between two OUT retirements. The generator sums the
phase's non-WAIT instructions (1 cycle each, DR 0001) and sizes the one WAIT
so the span equals the budget exactly; the assembler's `.cyclesec` report
then states the same number independently.
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
OUT_DIR = ROOT / "firmware" / "asm"

# (name, L=t_LOW cycles, H=t_HIGH cycles, HD=t_HD;STA, SUSTA, SUSTO)
MODES = {
    "fast": dict(L=65, H=60, HD=65, SUSTA=30, SUSTO=60,
                 table="Fast-mode (400 kHz class)"),
    "std": dict(L=235, H=200, HD=205, SUSTA=235, SUSTO=205,
                table="Standard-mode (100 kHz class)"),
}

ADDR_W = 0xA0  # 0x50 << 1 | W
ADDR_R = 0xA1  # 0x50 << 1 | R
PTR = 0x5A     # the write-phase payload byte
POLL_EXTRA = 2  # cycles a polled rise phase adds (LDI + IN precede the hold)


class Builder:
    def __init__(self, mode, poll):
        self.p = MODES[mode]
        self.poll = poll
        self.lines = []
        self.poll_sites = 0

    def raw(self, text=""):
        self.lines.append(text)

    def phase(self, name, target, body, rise=False):
        """body: list of instruction strings (one may be the literal 'WAIT*').
        For a polled rise phase the poll block follows the first (OUT)
        instruction and the target grows by POLL_EXTRA."""
        body = list(body)
        if rise and self.poll:
            n = self.poll_sites
            self.poll_sites += 1
            body[1:1] = [
                "LDI   R3, 0x01       ; poll mask",
                f"poll{n}: IN    R2, UIO_IN   ; peripheral's SCL level",
                "AND   R2, R3",
                f"BZ    poll{n}          ; SCL held low -> poll again",
            ]
            target += POLL_EXTRA
        fixed = sum(1 for b in body if not b.startswith("WAIT*"))
        has_wait = any(b.startswith("WAIT*") for b in body)
        slack = target - fixed
        assert slack >= (1 if has_wait else 0), (name, target, fixed)
        self.raw(f".cyclesec {name}")
        for b in body:
            if b.startswith("WAIT*"):
                tag = b[5:].strip()
                if slack - 1 > 255:
                    raise ValueError(f"{name}: WAIT {slack - 1} > 255")
                self.raw(
                    f"        WAIT  {slack - 1}"
                    f"{' ' * (3 - len(str(slack - 1)))}"
                    f"      ; {slack} cycles{(' ' + tag) if tag else ''}"
                )
            else:
                self.raw("        " + b)
        self.raw(".endcyclesec")
        return slack


def first_bit_pins(inv):
    """Instructions that leave R0 = ~byte, R1 = 8, R3 = SCL-low pins whose
    SDA is the byte's MSB (AND isolates the inverted bit, XOR flips it, so
    that after eight SHFs R0 = 0 yields SDA released = 0x80)."""
    return [
        f"LDI   R0, 0x{inv:02X}       ; ~byte (inverted-data trick)",
        "LDI   R1, 0x08       ; bit counter",
        "MOV   R3, R0",
        "LDI   R2, 0x80",
        "AND   R3, R2",
        "XOR   R3, R2         ; R3 = SDA(bit 1), SCL low",
    ]


def next_pins_only():
    return [
        "MOV   R3, R0",
        "LDI   R2, 0x80",
        "AND   R3, R2",
        "XOR   R3, R2         ; R3 = SDA(bit 1), SCL low",
    ]


def build(mode, poll):
    b = Builder(mode, poll)
    P = b.p
    L, H, HD, SUSTA, SUSTO = P["L"], P["H"], P["HD"], P["SUSTA"], P["SUSTO"]
    variant = "poll" if poll else "exact"
    name = f"i2c_{mode}_sr" + ("_poll" if poll else "")
    inv = lambda v: (~v) & 0xFF

    b.raw(f"""; {name}.asm -- bit-banged I2C controller, {P['table']} phase budget:
; write -> repeated START -> read (issue #92, part of #23). GENERATED by
; firmware/tools/gen_i2c_sr.py -- the four i2c_*_sr*.asm programs share one
; instruction stream and differ only in phase literals and the SCL poll.
;
; Transfer: START, 0xA0 (0x50 W) + ACK, 0x5A + ACK, repeated START, 0xA1
; (0x50 R) + ACK, ONE read byte driven by the peripheral and acknowledged
; by NOTHING (the controller releases SDA on the 9th clock: NACK), STOP.
; The received byte is published on UO_OUT before HALT so the bench can
; check what the core actually shifted in from the bus.
;
; Pin plan (same as i2c_fast.asm / i2c_std.asm): UIO_OUT bit 0 = SCL,
; bit 7 = SDA, writing 1 RELEASES the line. The bench composes the
; wired-AND from uio_out/uio_in (uio_oe is fixed to 0 at the top level;
; DR 0008 / #75 owns the silicon-true open-drain half).
;
; Budgets (cycles): t_LOW {L}, t_HIGH {H}, t_HD;STA {HD}, t_SU;STA {SUSTA},
; t_SU;STO {SUSTO}.  t_SU;STA is the span from the SCL rise that precedes the
; repeated START to the OUT that pulls SDA low, i.e. the UM10204 Table 10
; setup time, here paced AT the Table 10 minimum.""")
    if poll:
        b.raw(f"""; Variant: SCL POLLING. After EVERY SCL rise (data, ACK, repeated START and
; STOP) the program polls the peripheral's SCL level (IN uio_in bit 0) and
; loops while it reads low -- clock stretching (UM10204 section 3.1.9).
; The poll costs {POLL_EXTRA} extra cycles per rise phase (LDI + IN precede the
; hold) so the hold after the IN that sees SCL high is the full budget: an
; unstretched rise phase is budget+{POLL_EXTRA} cycles, and a stretched one is never
; shorter than the budget. DETERMINISM CLAIM: with the peripheral not
; stretching, every phase is exact and data-independent. When the peripheral
; stretches, the interval spent in a `poll` loop is data-dependent by
; design (it lasts as long as the peripheral holds SCL) and is EXCLUDED from
; the determinism claim; every other phase stays exact. The `BZ poll`
; instructions are the program's only data-dependent branches (DR 0001's
; sanctioned handshake branch; the assembler's lint warns on each, one per
; polled rise, and the bench asserts that exact count).""")
    else:
        b.raw("""; Variant: EXACT. No pin-dependent branch anywhere: every phase length is
; an assemble-time literal, the assembler lint is silent, and the whole
; transfer is fully deterministic. It does not tolerate clock stretching.""")
    b.raw(f"""; The bit loops need a counter, and the ISA has four registers, so the
; loop keeps R0 = ~byte (shifted left; after 8 shifts it is 0, which the
; AND/XOR pin recipe turns into SDA released for the following ACK slot),
; R1 = counter, R2 = scratch (constants are re-LDI'd where needed), R3 =
; the pin value for the next OUT. LDI/MOV/SHF/OUT/BNZ are 1 cycle each
; (taken or not), so the loop-back costs no extra cycle in any phase.
;
; `.cyclesec` convention (same as i2c_fast.asm): a section opens AT the OUT
; that starts a phase and closes before the OUT that ends it, so its
; cycle count IS the phase's measured length.
""")
    b.raw("; ---------------------------------------------------------------- setup")
    b.raw("        LDI   R3, 0x81        ; both lines released: bus idle")
    b.raw("        OUT   UIO_OUT, R3")
    b.raw("        WAIT  255             ; idle bus before the START")
    b.raw("        LDI   R3, 0x01        ; SCL high, SDA low")
    b.raw("; --------------------------------------------------------------- START")
    b.phase("i2c_start_hold", HD,
            ["OUT   UIO_OUT, R3   ; START: SDA falls while SCL high"]
            + first_bit_pins(inv(ADDR_W)) + ["WAIT*"])

    def tx_byte(n, byte_label):
        b.raw(f"; ------------------------------------------ byte {n}: {byte_label}")
        b.raw(f"tx{n}_loop:")
        b.phase(f"i2c_tx{n}_low", L,
                ["OUT   UIO_OUT, R3   ; SCL falls, SDA = data bit",
                 "WAIT*",
                 "LDI   R2, 0x01",
                 "OR    R3, R2         ; raise SCL, SDA unchanged"])
        b.phase(f"i2c_tx{n}_high", H,
                ["OUT   UIO_OUT, R3   ; SCL rises: bit sampled on the line",
                 "WAIT*",
                 "SHF   R0, LEFT       ; next bit into position",
                 "MOV   R3, R0",
                 "LDI   R2, 0x80",
                 "AND   R3, R2",
                 "XOR   R3, R2         ; R3 = next SDA, SCL low",
                 "LDI   R2, 0x01",
                 "SUB   R1, R2         ; counter--  (sets Z)",
                 f"BNZ   tx{n}_loop      ; 8 data clocks"], rise=True)
        b.phase(f"i2c_ack{n}_low", L,
                ["OUT   UIO_OUT, R3   ; 9th clock: SCL falls, SDA released",
                 "LDI   R3, 0x81",
                 "WAIT*"])

    # ---- byte 1: address + W
    tx_byte(1, "address 0xA0 (0x50 W)")
    b.phase("i2c_ack1_high", H,
            ["OUT   UIO_OUT, R3   ; ACK clock rises (peripheral pulls SDA)"]
            + first_bit_pins(inv(PTR)) + ["WAIT*"], rise=True)
    # ---- byte 2: payload
    tx_byte(2, "payload 0x5A")
    b.phase("i2c_ack2_high", H,
            ["OUT   UIO_OUT, R3   ; ACK clock rises",
             "LDI   R3, 0x80       ; SCL low, SDA released (for the Sr)",
             "WAIT*"], rise=True)
    # ---- repeated START
    b.raw("; ------------------------------------------------- repeated START")
    b.phase("i2c_sr_low", L,
            ["OUT   UIO_OUT, R3   ; SCL falls, SDA released (high)",
             "LDI   R3, 0x81",
             "LDI   R0, 0x%02X       ; ~0xA1 for the next byte" % inv(ADDR_R),
             "LDI   R1, 0x08",
             "WAIT*"])
    b.phase("i2c_sr_rise", SUSTA,
            ["OUT   UIO_OUT, R3   ; SCL rises with SDA high: Sr setup begins",
             "LDI   R3, 0x01       ; SCL high, SDA low",
             "WAIT* NEGCTL-SUSTA"], rise=True)
    b.phase("i2c_sr_hold", HD,
            ["OUT   UIO_OUT, R3   ; repeated START: SDA falls while SCL high"]
            + next_pins_only() + ["WAIT*"])
    # ---- byte 3: address + R
    tx_byte(3, "address 0xA1 (0x50 R)")
    b.phase("i2c_ack3_high", H,
            ["OUT   UIO_OUT, R3   ; ACK clock rises",
             "LDI   R0, 0x00       ; receive accumulator",
             "LDI   R1, 0x08",
             "LDI   R3, 0x80       ; SCL low, SDA released",
             "WAIT*"], rise=True)
    # ---- read byte
    b.raw("; ----------------------------------- read byte (peripheral drives SDA)")
    b.raw("rd_loop:")
    b.phase("i2c_rd_low", L,
            ["OUT   UIO_OUT, R3   ; SCL falls, SDA released to the peripheral",
             "LDI   R3, 0x81",
             "WAIT*"])
    b.phase("i2c_rd_high", H,
            ["OUT   UIO_OUT, R3   ; SCL rises: peripheral's bit is on the line",
             "IN    R2, UIO_IN     ; sample the bus",
             "LDI   R3, 0x80       ; mask AND next SCL-low pins",
             "AND   R2, R3         ; isolate SDA (bit 7)",
             "SHF   R2, RIGHT", "SHF   R2, RIGHT", "SHF   R2, RIGHT",
             "SHF   R2, RIGHT", "SHF   R2, RIGHT", "SHF   R2, RIGHT",
             "SHF   R2, RIGHT      ; bit 7 -> bit 0",
             "SHF   R0, LEFT",
             "OR    R0, R2         ; MSB first",
             "WAIT*",
             "LDI   R2, 0x01",
             "SUB   R1, R2         ; counter--  (sets Z)",
             "BNZ   rd_loop        ; 8 data clocks"], rise=True)
    b.phase("i2c_nack_low", L,
            ["OUT   UIO_OUT, R3   ; 9th clock: SCL falls, SDA stays released",
             "LDI   R3, 0x81",
             "WAIT*"])
    b.phase("i2c_nack_high", H,
            ["OUT   UIO_OUT, R3   ; SCL rises, SDA released: controller NACK",
             "LDI   R3, 0x80",
             "WAIT*"], rise=True)
    b.raw("; ------------------------------------------------------------- STOP")
    b.phase("i2c_stop_low", L,
            ["OUT   UIO_OUT, R3   ; SCL falls, SDA released",
             "LDI   R3, 0x00       ; SDA low during the low period",
             "OUT   UIO_OUT, R3",
             "WAIT*",
             "LDI   R3, 0x01       ; SCL high, SDA low"])
    b.phase("i2c_stop_setup", SUSTO,
            ["OUT   UIO_OUT, R3   ; SCL rises: STOP setup begins",
             "LDI   R3, 0x81       ; SDA released",
             "WAIT*"], rise=True)
    b.raw("        OUT   UIO_OUT, R3     ; SDA rises while SCL high: STOP")
    b.raw("        OUT   UO_OUT, R0      ; publish the received byte")
    b.raw("        WAIT  255             ; hold the bus idle")
    b.raw("        HALT")
    return name, "\n".join(b.lines) + "\n", b.poll_sites


def main(argv):
    check = "--check" in argv
    drift = False
    for mode in MODES:
        for poll in (False, True):
            name, text, _sites = build(mode, poll)
            path = OUT_DIR / f"{name}.asm"
            if check:
                if not path.exists() or path.read_text() != text:
                    print(f"DRIFT {path}")
                    drift = True
            else:
                path.write_text(text)
                print(f"wrote {path}")
    return 1 if drift else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
