; spi_10.asm -- GENERATED by verification/firmware_templates.py
; (issue #93). seed=20261009 protocol=spi index=10
; params={"cpha": 0, "cpol": 1, "half_period": 6, "miso": [117], "mode": 2, "mosi": [170]}
; Regenerate: python3 verification/firmware_templates.py --seed 20261009 --out DIR
        LDI   R2, 0x09      ; CS released, SCLK idle
        OUT   UIO_OUT, R2      ; idle image before the drivers are on
        LDI   R3, 0x0B      ; CS|MOSI|SCLK
        WCTL  UIO_DIR, R3      ; DR 0012: push-pull
        WAIT  13
; ---- burst 0: MOSI 0xAA
        LDI   R2, 0x08      ; CS asserted
        OUT   UIO_OUT, R2
        WAIT  3
        LDI   R1, 0x08
        LDI   R2, 0x02
.cyclesec spi_rand_b0
        OUT   UIO_OUT, R2
        IN    R3, UIO_IN
        WAIT  3
        OUT   UIO_OUT, R1
        LDI   R2, 0x00
        WAIT  3
        OUT   UIO_OUT, R2
        IN    R3, UIO_IN
        WAIT  3
        OUT   UIO_OUT, R1
        LDI   R2, 0x02
        WAIT  3
        OUT   UIO_OUT, R2
        IN    R3, UIO_IN
        WAIT  3
        OUT   UIO_OUT, R1
        LDI   R2, 0x00
        WAIT  3
        OUT   UIO_OUT, R2
        IN    R3, UIO_IN
        WAIT  3
        OUT   UIO_OUT, R1
        LDI   R2, 0x02
        WAIT  3
        OUT   UIO_OUT, R2
        IN    R3, UIO_IN
        WAIT  3
        OUT   UIO_OUT, R1
        LDI   R2, 0x00
        WAIT  3
        OUT   UIO_OUT, R2
        IN    R3, UIO_IN
        WAIT  3
        OUT   UIO_OUT, R1
        LDI   R2, 0x02
        WAIT  3
        OUT   UIO_OUT, R2
        IN    R3, UIO_IN
        WAIT  3
        OUT   UIO_OUT, R1
        LDI   R2, 0x00
        WAIT  3
        OUT   UIO_OUT, R2
        IN    R3, UIO_IN
        WAIT  3
        OUT   UIO_OUT, R1
        LDI   R2, 0x00
        WAIT  3
.endcyclesec
        WAIT  3
        LDI   R2, 0x09      ; CS released
        OUT   UIO_OUT, R2
        WAIT  31
        HALT
