; spi_08.asm -- GENERATED by verification/firmware_templates.py
; (issue #93). seed=20261009 protocol=spi index=8
; params={"cpha": 0, "cpol": 0, "half_period": 4, "miso": [174, 19], "mode": 0, "mosi": [85, 255]}
; Regenerate: python3 verification/firmware_templates.py --seed 20261009 --out DIR
        LDI   R2, 0x01      ; CS released, SCLK idle
        OUT   UO_OUT, R2
        WAIT  15
; ---- burst 0: MOSI 0x55
        LDI   R2, 0x00      ; CS asserted
        OUT   UO_OUT, R2
        WAIT  3
        LDI   R1, 0x00
        LDI   R2, 0x02
.cyclesec spi_rand_b0
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        WAIT  1
        OUT   UO_OUT, R1
        LDI   R2, 0x06
        WAIT  1
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        WAIT  1
        OUT   UO_OUT, R1
        LDI   R2, 0x02
        WAIT  1
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        WAIT  1
        OUT   UO_OUT, R1
        LDI   R2, 0x06
        WAIT  1
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        WAIT  1
        OUT   UO_OUT, R1
        LDI   R2, 0x02
        WAIT  1
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        WAIT  1
        OUT   UO_OUT, R1
        LDI   R2, 0x06
        WAIT  1
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        WAIT  1
        OUT   UO_OUT, R1
        LDI   R2, 0x02
        WAIT  1
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        WAIT  1
        OUT   UO_OUT, R1
        LDI   R2, 0x06
        WAIT  1
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        WAIT  1
        OUT   UO_OUT, R1
        LDI   R2, 0x00
        WAIT  1
.endcyclesec
        WAIT  3
        LDI   R2, 0x01      ; CS released
        OUT   UO_OUT, R2
        WAIT  31
; ---- burst 1: MOSI 0xFF
        LDI   R2, 0x00      ; CS asserted
        OUT   UO_OUT, R2
        WAIT  3
        LDI   R1, 0x00
        LDI   R2, 0x06
.cyclesec spi_rand_b1
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        WAIT  1
        OUT   UO_OUT, R1
        LDI   R2, 0x06
        WAIT  1
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        WAIT  1
        OUT   UO_OUT, R1
        LDI   R2, 0x06
        WAIT  1
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        WAIT  1
        OUT   UO_OUT, R1
        LDI   R2, 0x06
        WAIT  1
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        WAIT  1
        OUT   UO_OUT, R1
        LDI   R2, 0x06
        WAIT  1
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        WAIT  1
        OUT   UO_OUT, R1
        LDI   R2, 0x06
        WAIT  1
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        WAIT  1
        OUT   UO_OUT, R1
        LDI   R2, 0x06
        WAIT  1
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        WAIT  1
        OUT   UO_OUT, R1
        LDI   R2, 0x06
        WAIT  1
        OUT   UO_OUT, R2
        IN    R3, UIO_IN
        WAIT  1
        OUT   UO_OUT, R1
        LDI   R2, 0x00
        WAIT  1
.endcyclesec
        WAIT  3
        LDI   R2, 0x01      ; CS released
        OUT   UO_OUT, R2
        WAIT  31
        HALT
